In [1]:
from calculations.Composition.Composition import Composition
from calculations.Utils.Conditions import Conditions
from calculations.CompositionalModel.CompositionalModel import CompositionalModel
from calculations.EOS.PenelouxVolumeCorrection import PenelouxVolumeCorrection
from calculations.Utils.ResultsViewer import FlashResultsViewer, DLEResultsViewer, SeparatorTestResultsViewer, StandardSeparationResultsViewer
from calculations.Utils.CompositionLoader import CompositionExcelLoader
from calculations.PhaseDiagram.PhaseDiagram_v4 import PhaseDiagram
import seaborn as sns
import matplotlib.pyplot as plt

# KRSNLN

In [ ]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\krsnln.xlsx')
krsnln_dict = excel_loader.load(header=True, sheet='to_model')

In [ ]:
krsnln_rizari_daubert_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'rizari_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_rizari_daubert_composition.edit_component_properties('C36', {'molar_mass' : 650.009})

krsnln_pedersen_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_pedersen_composition.edit_component_properties('C36', {'molar_mass' : 650.009})

krsnln_pedersen_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_pedersen_composition.edit_component_properties('C36', {'molar_mass' : 650.009})

krsnln_kesler_lee_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'kesler_lee',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
# krsnln_kesler_lee_composition.edit_component_properties('C36', {'molar_mass' : 650.009})

krsnln_sim_daubert_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'sim_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_sim_daubert_composition.edit_component_properties('C36', {'molar_mass' : 650.009})

krsnln_standing_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'standing',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_standing_composition.edit_component_properties('C36', {'molar_mass' : 650.009})

krsnln_twu_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'twu',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_twu_composition.edit_component_properties('C36', {'molar_mass' : 650.009})

krsnln_brs_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'pc_from_eos',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_brs_composition.edit_component_properties('C36', {'molar_mass' : 650.009})

krsnln_cavett_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'cavett',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_cavett_composition.edit_component_properties('C36', {'molar_mass' : 650.009})

## Фазовые

###  Расчет

In [ ]:
phase_env_rizari_daubert = PhaseDiagram(zi = krsnln_rizari_daubert_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_rizari_daubert.calc_phase_diagram('PREOS')
phase_env_rizari_data = phase_env_rizari_daubert.get_phase_diagram_data()

In [ ]:
phase_env_pedersen = PhaseDiagram(zi = krsnln_pedersen_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_pedersen.calc_phase_diagram('PREOS')
phase_env_pedersen_data = phase_env_pedersen.get_phase_diagram_data()

In [ ]:
phase_env_kesler_lee = PhaseDiagram(zi = krsnln_kesler_lee_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_kesler_lee.calc_phase_diagram('PREOS')
phase_env_kesler_lee_data = phase_env_kesler_lee.get_phase_diagram_data()

In [ ]:
phase_env_sim_daubert = PhaseDiagram(zi = krsnln_sim_daubert_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_sim_daubert.calc_phase_diagram('PREOS')
phase_env_sim_daubert_data = phase_env_sim_daubert.get_phase_diagram_data()

In [ ]:
phase_env_twu = PhaseDiagram(zi = krsnln_twu_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_twu.calc_phase_diagram('PREOS')
phase_env_twu_data = phase_env_twu.get_phase_diagram_data()

In [ ]:
phase_env_brs = PhaseDiagram(zi = krsnln_brs_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_brs.calc_phase_diagram('PREOS')
phase_env_brs_data = phase_env_brs.get_phase_diagram_data()

### Сводный график

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns


sns.lineplot(marker='',data = phase_env_rizari_data, x= phase_env_rizari_data['Temp'], y= phase_env_rizari_data['Up'], color = 'blue', label = 'Rizari-Daubert')
sns.lineplot(marker='',data = phase_env_rizari_data, x= phase_env_rizari_data['Temp'], y= phase_env_rizari_data['Low'], color = 'blue')
sns.lineplot(marker='',data = phase_env_pedersen_data, x= phase_env_pedersen_data['Temp'], y= phase_env_pedersen_data['Up'], color = 'red', label = 'Pedersen')
sns.lineplot(marker='',data = phase_env_pedersen_data, x= phase_env_pedersen_data['Temp'], y= phase_env_pedersen_data['Low'], color = 'red')
sns.lineplot(marker='',data = phase_env_kesler_lee_data, x= phase_env_kesler_lee_data['Temp'], y= phase_env_kesler_lee_data['Up'], color = 'green', label = 'Kesler_lee')
sns.lineplot(marker='',data = phase_env_kesler_lee_data, x= phase_env_kesler_lee_data['Temp'], y= phase_env_kesler_lee_data['Low'], color = 'green')
sns.lineplot(marker='',data = phase_env_sim_daubert_data, x= phase_env_sim_daubert_data['Temp'], y= phase_env_sim_daubert_data['Up'], color = 'blue', label = 'Sim_Daubert')
sns.lineplot(marker='',data = phase_env_sim_daubert_data, x= phase_env_sim_daubert_data['Temp'], y= phase_env_sim_daubert_data['Low'], color = 'blue')
# sns.lineplot(marker='o',data = phase_env_standing_data, x= phase_env_standing_data['Temp'], y= phase_env_standing_data['Up'], color = 'gray', label = 'Standing')
# sns.lineplot(marker='o',data = phase_env_standing_data, x= phase_env_standing_data['Temp'], y= phase_env_standing_data['Low'], color = 'gray')

# sns.lineplot(marker='o',data = phase_env_twu_data, x= phase_env_twu_data['Temp'], y= phase_env_twu_data['Up'], color = 'yellow', label = 'Twu')
# sns.lineplot(marker='o',data = phase_env_twu_data, x= phase_env_twu_data['Temp'], y= phase_env_twu_data['Low'], color = 'yellow')

sns.lineplot(marker='',data = phase_env_brs_data, x= phase_env_brs_data['Temp'], y= phase_env_brs_data['Up'], color = 'black', label = 'Brusilovsky')
sns.lineplot(marker='',data = phase_env_brs_data, x= phase_env_brs_data['Temp'], y= phase_env_brs_data['Low'], color = 'black')

sns.scatterplot(x=[110], y = [21.2], color = 'green', label = 'Psat_fact', marker ='o')
plt.title('Krasnoleninskoe Phase Envelope')
plt.xlabel('Temperature, C')
plt.ylabel('Pressure, MPa')

## Сепаратор

In [ ]:
krsnl_rd_model = CompositionalModel(krsnln_rizari_daubert_composition)
krsnl_ped_model = CompositionalModel(krsnln_pedersen_composition)
krsnl_kl_model = CompositionalModel(krsnln_kesler_lee_composition)
krsnl_sd_model = CompositionalModel(krsnln_sim_daubert_composition)
krsnl_brs_model = CompositionalModel(krsnln_brs_composition)

In [ ]:
krsnl_rd_model.experiments.SEPARATORTEST_MOD.calculate(23.4, 110, [0.55, 0.16], [25,25])
krsnl_ped_model.experiments.SEPARATORTEST_MOD.calculate(23.4, 110, [0.55, 0.16], [25,25])
krsnl_kl_model.experiments.SEPARATORTEST_MOD.calculate(23.4, 110, [0.55, 0.16], [25,25])
krsnl_sd_model.experiments.SEPARATORTEST_MOD.calculate(23.4, 110, [0.55, 0.16], [25,25])
krsnl_brs_model.experiments.SEPARATORTEST_MOD.calculate(23.4, 110, [0.55, 0.16], [25,25])

In [ ]:
dle_res_view = DLEResultsViewer()
dle_res_view.view(krsnl_ped_model.experiments.SEPARATORTEST_MOD.result)

In [ ]:
sns.lineplot(marker='o', x= krsnl_rd_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_rd_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'gray', label = 'Rizari-Daubert')
sns.lineplot(marker='', x= krsnl_ped_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_ped_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'red', label = 'Pedersen')
sns.lineplot(marker='o', x= krsnl_kl_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_kl_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'blue', label = 'kesler-Lee')
sns.lineplot(marker='', x= krsnl_sd_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_sd_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= krsnl_brs_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_brs_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='X', x = [30, 21.2, 0.55, 0.16, 0], y = [158.85, 158.85, 13.33, 6.14, 0], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test GOR sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='o', x= krsnl_rd_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_rd_model.experiments.SEPARATORTEST_MOD.result.bo, color = 'gray', label = 'Rizari-Daubert')
sns.lineplot(marker='o', x= krsnl_ped_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_ped_model.experiments.SEPARATORTEST_MOD.result.bo, color = 'red', label = 'Pedersen')
sns.lineplot(marker='', x= krsnl_kl_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_kl_model.experiments.SEPARATORTEST_MOD.result.bo, color = 'blue', label = 'kesler-Lee')
sns.lineplot(marker='o', x= krsnl_sd_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_sd_model.experiments.SEPARATORTEST_MOD.result.bo, color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= krsnl_brs_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_brs_model.experiments.SEPARATORTEST_MOD.result.bo, color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='X', x = [30, 21.2, 0.55, 0.16, 0], y = [1.523, 1.559, 1.048, 1.027, 1], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test Bo sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='o', x= krsnl_rd_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_rd_model.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'gray', label = '120% Pc')
sns.lineplot(marker='', x= krsnl_ped_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_ped_model.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'red', label = '110% Pc')
sns.lineplot(marker='o', x= krsnl_kl_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_kl_model.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'blue', label = 'base Pc')
sns.lineplot(marker='', x= krsnl_sd_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_sd_model.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'green', label = '90% Pc')
sns.lineplot(marker='', x= krsnl_brs_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= krsnl_brs_model.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'orange', label = '80% Pc')
sns.lineplot(marker='X', x = [30, 21.2, 0.55, 0.16, 0], y = [0.6447, 0.6298, 0.8032, 0.8098, 0.8208], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test Oden sensetivity to critial pressure')

## УРС

In [ ]:
krsnl_brs_model = CompositionalModel(krsnln_kesler_lee_composition, eos = 'BRSEOS')
krsnl_pr_model = CompositionalModel(krsnln_kesler_lee_composition, eos = 'PREOS')
krsnl_srk_model = CompositionalModel(krsnln_kesler_lee_composition, eos = 'SRKEOS')

In [ ]:
krsnl_pr_model.saturation_pressure(110)

In [ ]:
krsnl_srk_model.saturation_pressure(110)

In [ ]:
krsnl_brs_model.saturation_pressure(110)

In [ ]:
krsnl_brs_model.experiments.SEPARATORTEST_MOD.calculate(23.4, 200, [0.55, 0.16], [25,25])
krsnl_pr_model.experiments.SEPARATORTEST_MOD.calculate(23.4, 200, [0.55, 0.16], [25,25])
krsnl_srk_model.experiments.SEPARATORTEST_MOD.calculate(23.4, 200, [0.55, 0.16], [25,25])

In [ ]:
krsnl_brs_model.flash(Conditions(10, 110))

In [ ]:
krsnl_brs_model.experiments.STANDARDSEPARATION.calculate(23.4, 110)

In [ ]:
phase_env_brs = PhaseDiagram(zi = krsnln_rizari_daubert_composition, p_max=40, t_max=660, t_min=0, t_step=10)
phase_env_brs.calc_phase_diagram('BRSEOS')
phase_env_brs_data = phase_env_brs.get_phase_diagram_data()

In [ ]:
phase_env_pr = PhaseDiagram(zi = krsnln_rizari_daubert_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_pr.calc_phase_diagram('SRKEOS')
phase_env_pr_data = phase_env_pr.get_phase_diagram_data()

# PRRZLM MDT

In [ ]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\prrzlm_mdt.xlsx')
przlm_dict = excel_loader.load(header=True, sheet='to_model')

## Создаем базовую модель и сравниваемся с PVTSIM

In [ ]:
przlm_comp = Composition(przlm_dict)

In [ ]:
przlm_comp.COMPOSITION_PROPERTIES

In [ ]:
przlm_model = CompositionalModel(przlm_comp, eos = 'PREOS')

In [ ]:
conds = Conditions(5,50)

In [ ]:
przlm_model.flash(conds)

In [ ]:
przlm_model.saturation_pressure(65)

### Проверяем сепаратор тест

In [ ]:
przlm_model.experiments.SEPARATORTEST.calculate_3stages([0.7, 0.5, 0.1], [20, 20, 20])

## Начинаем играть корреляциями для фазовой

### Расчет фазовой по корреляции Ризари-Дауберта

In [ ]:
prr_rizari_daubert = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'rizari_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
prr_rizari_daubert.edit_component_properties('C30', {'molar_mass' : 727.35})

In [ ]:
phase_env_prr_rizari_daubert = PhaseDiagram(prr_rizari_daubert, p_max=30, t_max= 550, t_min=0, t_step=10)

In [ ]:
phase_env_prr_rizari_daubert.calc_phase_diagram('PREOS')

In [ ]:
phase_env_data_1 = phase_env_prr_rizari_daubert.get_phase_diagram_data()

### Расчет фазовой по корреляции Pedersen

In [ ]:
prr_pedersen_comp = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
prr_pedersen_comp.edit_component_properties('C30', {'molar_mass' : 727.35})

In [ ]:
phase_env_prr_pedersen = PhaseDiagram(prr_pedersen_comp, p_max=35, t_max= 550, t_min=0, t_step=10)
phase_env_prr_pedersen.calc_phase_diagram('PREOS')

In [ ]:
phase_env_data_2 = phase_env_prr_pedersen.get_phase_diagram_data()

In [ ]:
prr_pedersen_comp.COMPOSITION_PROPERTIES

### Расчет по корреляции Kesler-Lee

In [ ]:
prr_kesler_lee_comp = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'kesler_lee',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
prr_kesler_lee_comp.edit_component_properties('C30', {'molar_mass' : 727.35})

In [ ]:
phase_env_prr_kesler_lee = PhaseDiagram(prr_kesler_lee_comp, p_max=35, t_max= 550, t_min=0, t_step=10)
phase_env_prr_kesler_lee.calc_phase_diagram('PREOS')

In [ ]:
phase_env_data_3 = phase_env_prr_kesler_lee.get_phase_diagram_data()

###  Расчет по корреляции Sim-Daubert

In [ ]:
prr_sim_daubert_comp = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'sim_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
prr_sim_daubert_comp.edit_component_properties('C30', {'molar_mass' : 727.35})

In [ ]:
prr_sim_daubert_comp.COMPOSITION_PROPERTIES

In [ ]:
phase_env_prr_sim_daubert = PhaseDiagram(prr_sim_daubert_comp, p_max=35, t_max= 550, t_min=0, t_step=10)
phase_env_prr_sim_daubert.calc_phase_diagram('PREOS')

In [ ]:
phase_env_data_4 = phase_env_prr_sim_daubert.get_phase_diagram_data()

### Pc Br

In [ ]:
prr_pc_eos_comp = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'pc_from_eos',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
prr_pc_eos_comp.edit_component_properties('C30', {'molar_mass' : 727.35})

In [ ]:
phase_env_prr_brs = PhaseDiagram(prr_pc_eos_comp, p_max=35, t_max= 550, t_min=0, t_step=10)
phase_env_prr_brs.calc_phase_diagram('PREOS')
phase_env_data_5 = phase_env_prr_brs.get_phase_diagram_data()

### Построение общей фазовой и сравнение результатов

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns


sns.lineplot(marker='o',data = phase_env_data_1, x= phase_env_data_1['Temp'], y= phase_env_data_1['Up'], color = 'blue', label = 'Rizari-Daubert')
sns.lineplot(marker='o',data = phase_env_data_1, x= phase_env_data_1['Temp'], y= phase_env_data_1['Low'], color = 'blue')
sns.lineplot(marker='o',data = phase_env_data_2, x= phase_env_data_2['Temp'], y= phase_env_data_2['Up'], color = 'red', label = 'Pedersen')
sns.lineplot(marker='o',data = phase_env_data_2, x= phase_env_data_2['Temp'], y= phase_env_data_2['Low'], color = 'red')
sns.lineplot(marker='',data = phase_env_data_3, x= phase_env_data_3['Temp'], y= phase_env_data_3['Up'], color = 'gray', label = 'Kesler-Lee')
sns.lineplot(marker='',data = phase_env_data_3, x= phase_env_data_3['Temp'], y= phase_env_data_3['Low'], color = 'gray')
sns.lineplot(marker='',data = phase_env_data_4, x= phase_env_data_4['Temp'], y= phase_env_data_4['Up'], color = 'black', label = 'Sim-Daubert')
sns.lineplot(marker='',data = phase_env_data_4, x= phase_env_data_4['Temp'], y= phase_env_data_4['Low'], color = 'black')
sns.lineplot(marker='',data = phase_env_data_5, x= phase_env_data_5['Temp'], y= phase_env_data_5['Up'], color = 'green', label = 'Brusilovsky')
sns.lineplot(marker='',data = phase_env_data_5, x= phase_env_data_5['Temp'], y= phase_env_data_5['Low'], color = 'green')
sns.scatterplot(x=[65.6], y = [13.2], color = 'green', label = 'Psat_fact')
plt.title('Prirazlomnoe Phase Envelope')
plt.xlabel('Temperature, C')
plt.ylabel('Pressure, MPa')

In [ ]:
model_rizari_daubert = CompositionalModel(prr_rizari_daubert)
model_pedersen = CompositionalModel(prr_pedersen_comp)
model_kesler_lee = CompositionalModel(prr_kesler_lee_comp)
model_sim_daubert = CompositionalModel(prr_sim_daubert_comp)
model_brusilovsky = CompositionalModel(prr_pc_eos_comp)

## Расчеты сепаратор теста

In [ ]:
model_rizari_daubert.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
model_pedersen.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
model_kesler_lee.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
model_sim_daubert.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
model_brusilovsky.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])

In [ ]:
sns.lineplot(marker='', x= model_rizari_daubert.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_rizari_daubert.experiments.SEPARATORTEST_MOD.result.rs, color = 'gray', label = 'Rizari-Daubert')
sns.lineplot(marker='', x= model_pedersen.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pedersen.experiments.SEPARATORTEST_MOD.result.rs, color = 'red', label = 'Pedersen')
sns.lineplot(marker='', x= model_kesler_lee.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_kesler_lee.experiments.SEPARATORTEST_MOD.result.rs, color = 'blue', label = 'Kesler-Lee')
sns.lineplot(marker='', x= model_sim_daubert.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_sim_daubert.experiments.SEPARATORTEST_MOD.result.rs, color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= model_brusilovsky.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_brusilovsky.experiments.SEPARATORTEST_MOD.result.rs, color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='o', x = [0.1013, 0.81, 13.18, 25.28], y = [0, 2.8, 40.4, 40.4], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test GOR sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='', x= model_rizari_daubert.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_rizari_daubert.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'gray', label = 'Rizari-Daubert')
sns.lineplot(marker='', x= model_pedersen.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pedersen.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'red', label = 'Pedersen')
sns.lineplot(marker='', x= model_kesler_lee.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_kesler_lee.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'blue', label = 'Kesler-Lee')
sns.lineplot(marker='', x= model_sim_daubert.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_sim_daubert.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= model_brusilovsky.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_brusilovsky.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='o', x = [0.1013, 0.81, 13.18, 25.28], y = [0.9298, 0.9223, 0.8775, 0.8859], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('Liquid density, g/sm3')
plt.title('Separator test liquid density sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='', x= model_rizari_daubert.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_rizari_daubert.experiments.SEPARATORTEST_MOD.result.bo, color = 'gray', label = 'Rizari-Daubert')
sns.lineplot(marker='', x= model_pedersen.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pedersen.experiments.SEPARATORTEST_MOD.result.bo, color = 'red', label = 'Pedersen')
sns.lineplot(marker='', x= model_kesler_lee.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_kesler_lee.experiments.SEPARATORTEST_MOD.result.bo, color = 'blue', label = 'Kesler-Lee')
sns.lineplot(marker='', x= model_sim_daubert.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_sim_daubert.experiments.SEPARATORTEST_MOD.result.bo, color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= model_brusilovsky.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_brusilovsky.experiments.SEPARATORTEST_MOD.result.bo, color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='o', x = [0.1013, 0.81, 13.18, 25.28], y = [1, 1.011, 1.1, 1.089], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('Liquid density, g/sm3')
plt.title('Separator test liquid density sensetivity to critial pressure')

## Расчеты DLE

In [ ]:
model_rizari_daubert.experiments.DLE.calculate(25.28, 65.6, [9.75, 7.34, 5.62, 2.86, 1.48, 0.1])
model_pedersen.experiments.DLE.calculate(25.28, 65.6, [9.75, 7.34, 5.62, 2.86, 1.48, 0.1])
model_kesler_lee.experiments.DLE.calculate(25.28, 65.6, [9.75, 7.34, 5.62, 2.86, 1.48, 0.1])
model_sim_daubert.experiments.DLE.calculate(25.28, 65.6, [9.75, 7.34, 5.62, 2.86, 1.48, 0.1])
model_brusilovsky.experiments.DLE.calculate(25.28, 65.6, [9.75, 7.34, 5.62, 2.86, 1.48, 0.1])

In [ ]:
przlm_dle_press_arr = [
25.28,
13.18,
9.75,
7.34,
5.62,
2.86,
1.48,
0.1,
0.1013,
]
przlm_dle_rs = [
44.6,
44.6,
36.1,
29.4,
24.3,
15.7,
11,
0,
0,
]

przlm_dle_bo = [
1.11,
1.121,
1.104,
1.091,
1.08,
1.064,
1.053,
1.03,
1
]

przlm_dle_z = [
0,
0,
0.9545,
0.9638,
0.9703,
0.9828,
0.9907,
1,
1,

]

In [ ]:
sns.lineplot(marker='o', x= model_rizari_daubert.experiments.DLE.result.pressure_arr, y= model_rizari_daubert.experiments.DLE.result.rs, color = 'gray', label = 'Rizari-Daubert')
sns.lineplot(marker='', x= model_pedersen.experiments.DLE.result.pressure_arr, y= model_pedersen.experiments.DLE.result.rs, color = 'red', label = 'Pedersen')
sns.lineplot(marker='o', x= model_kesler_lee.experiments.DLE.result.pressure_arr, y= model_kesler_lee.experiments.DLE.result.rs, color = 'blue', label = 'kesler-Lee')
sns.lineplot(marker='', x= model_sim_daubert.experiments.DLE.result.pressure_arr, y= model_sim_daubert.experiments.DLE.result.rs, color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= model_brusilovsky.experiments.DLE.result.pressure_arr, y= model_brusilovsky.experiments.DLE.result.rs, color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='X', x = przlm_dle_press_arr, y = przlm_dle_rs, label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('DLE GOR sensetivity to critial pressure')

## Расчеты УРС

In [ ]:
prrzlm_pr = CompositionalModel(przlm_comp, eos = 'PREOS')
prrzlm_srk = CompositionalModel(przlm_comp, eos = 'SRKEOS')
prrzlm_brs = CompositionalModel(przlm_comp, eos = 'BRSEOS')

In [ ]:
prrzlm_brs.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])

In [ ]:
prrzlm_pr.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])

In [ ]:
prrzlm_srk.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])

# ZAP_MES

In [ ]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\zap_mes.xlsx')
zap_mes_dict = excel_loader.load(header=True, sheet='to_model')

In [ ]:
zap_mes_comp = Composition(zap_mes_dict)
zap_mes_comp.edit_component_properties('C36', {'molar_mass':595.41})

In [ ]:
zms_rizari_daubert_composition = Composition(zi = zap_mes_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'rizari_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
zms_rizari_daubert_composition.edit_component_properties('C36', {'molar_mass' : 595.41})

zms_pedersen_composition = Composition(zi = zap_mes_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
zms_pedersen_composition.edit_component_properties('C36', {'molar_mass' : 595.41})

zms_pedersen_composition = Composition(zi = zap_mes_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
zms_pedersen_composition.edit_component_properties('C36', {'molar_mass' : 595.41})

zms_kesler_lee_composition = Composition(zi = zap_mes_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'kesler_lee',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
zms_kesler_lee_composition.edit_component_properties('C36', {'molar_mass' : 595.41})

zms_sim_daubert_composition = Composition(zi = zap_mes_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'sim_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
zms_sim_daubert_composition.edit_component_properties('C36', {'molar_mass' : 595.41})

zms_standing_composition = Composition(zi = zap_mes_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'standing',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
zms_standing_composition.edit_component_properties('C36', {'molar_mass' : 595.41})

zms_twu_composition = Composition(zi = zap_mes_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'twu',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
zms_twu_composition.edit_component_properties('C36', {'molar_mass' : 595.41})

zms_brs_composition = Composition(zi = zap_mes_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'pc_from_eos',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
zms_brs_composition.edit_component_properties('C36', {'molar_mass' : 595.41})

zms_cavett_composition = Composition(zi = zap_mes_dict, c6_plus_correlations= {'critical_temperature': 'kesler_lee',
                                                    'critical_pressure': 'cavett',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
zms_cavett_composition.edit_component_properties('C36', {'molar_mass' : 595.41})

## Фазовые от Рс

In [ ]:
phase_env_rizari_daubert = PhaseDiagram(zi = zms_rizari_daubert_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_rizari_daubert.calc_phase_diagram('PREOS')
phase_env_rizari_data = phase_env_rizari_daubert.get_phase_diagram_data()

In [ ]:
phase_env_pedersen = PhaseDiagram(zi = zms_pedersen_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_pedersen.calc_phase_diagram('PREOS')
phase_env_pedersen_data = phase_env_pedersen.get_phase_diagram_data()

In [ ]:
phase_env_kesler_lee = PhaseDiagram(zi = zms_kesler_lee_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_kesler_lee.calc_phase_diagram('PREOS')
phase_env_kesler_lee_data = phase_env_kesler_lee.get_phase_diagram_data()

In [ ]:
phase_env_sim_daubert = PhaseDiagram(zi = zms_sim_daubert_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_sim_daubert.calc_phase_diagram('PREOS')
phase_env_sim_daubert_data = phase_env_sim_daubert.get_phase_diagram_data()

In [ ]:
phase_env_brs = PhaseDiagram(zi = zms_brs_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_brs.calc_phase_diagram('PREOS')
phase_env_brs_data = phase_env_brs.get_phase_diagram_data()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns


sns.lineplot(marker='',data = phase_env_rizari_data, x= phase_env_rizari_data['Temp'], y= phase_env_rizari_data['Up'], color = 'blue', label = 'Rizari-Daubert')
sns.lineplot(marker='',data = phase_env_rizari_data, x= phase_env_rizari_data['Temp'], y= phase_env_rizari_data['Low'], color = 'blue')
sns.lineplot(marker='',data = phase_env_pedersen_data, x= phase_env_pedersen_data['Temp'], y= phase_env_pedersen_data['Up'], color = 'red', label = 'Pedersen')
sns.lineplot(marker='',data = phase_env_pedersen_data, x= phase_env_pedersen_data['Temp'], y= phase_env_pedersen_data['Low'], color = 'red')
sns.lineplot(marker='',data = phase_env_kesler_lee_data, x= phase_env_kesler_lee_data['Temp'], y= phase_env_kesler_lee_data['Up'], color = 'green', label = 'Kesler_lee')
sns.lineplot(marker='',data = phase_env_kesler_lee_data, x= phase_env_kesler_lee_data['Temp'], y= phase_env_kesler_lee_data['Low'], color = 'green')
sns.lineplot(marker='',data = phase_env_sim_daubert_data, x= phase_env_sim_daubert_data['Temp'], y= phase_env_sim_daubert_data['Up'], color = 'blue', label = 'Sim_Daubert')
sns.lineplot(marker='',data = phase_env_sim_daubert_data, x= phase_env_sim_daubert_data['Temp'], y= phase_env_sim_daubert_data['Low'], color = 'blue')
# sns.lineplot(marker='o',data = phase_env_standing_data, x= phase_env_standing_data['Temp'], y= phase_env_standing_data['Up'], color = 'gray', label = 'Standing')
# sns.lineplot(marker='o',data = phase_env_standing_data, x= phase_env_standing_data['Temp'], y= phase_env_standing_data['Low'], color = 'gray')

# sns.lineplot(marker='o',data = phase_env_twu_data, x= phase_env_twu_data['Temp'], y= phase_env_twu_data['Up'], color = 'yellow', label = 'Twu')
# sns.lineplot(marker='o',data = phase_env_twu_data, x= phase_env_twu_data['Temp'], y= phase_env_twu_data['Low'], color = 'yellow')

sns.lineplot(marker='',data = phase_env_brs_data, x= phase_env_brs_data['Temp'], y= phase_env_brs_data['Up'], color = 'black', label = 'Brusilovsky')
sns.lineplot(marker='',data = phase_env_brs_data, x= phase_env_brs_data['Temp'], y= phase_env_brs_data['Low'], color = 'black')

sns.scatterplot(x=[18], y = [7.38], color = 'green', label = 'Psat_fact', marker ='o')
plt.title('Zap Mess Phase Envelope')
plt.xlabel('Temperature, C')
plt.ylabel('Pressure, MPa')

## Сепаратор тест

In [ ]:
zms_rd_model = CompositionalModel(zms_rizari_daubert_composition)
zms_ped_model = CompositionalModel(zms_pedersen_composition)
zms_kl_model = CompositionalModel(zms_kesler_lee_composition)
zms_sd_model = CompositionalModel(zms_sim_daubert_composition)
zms_brs_model = CompositionalModel(zms_brs_composition)

In [ ]:
zms_rd_model.experiments.SEPARATORTEST_MOD.calculate(8, 18, [0.8, 0.3, 0.1], [20, 20, 20])
zms_ped_model.experiments.SEPARATORTEST_MOD.calculate(8, 18, [0.8, 0.3, 0.1], [20, 20, 20])
zms_kl_model.experiments.SEPARATORTEST_MOD.calculate(8, 18, [0.8, 0.3, 0.1], [20, 20, 20])
zms_sd_model.experiments.SEPARATORTEST_MOD.calculate(8, 18, [0.8, 0.3, 0.1], [20, 20, 20])
zms_brs_model.experiments.SEPARATORTEST_MOD.calculate(8, 18, [0.8, 0.3, 0.1], [20, 20, 20])

In [ ]:
sns.lineplot(marker='o', x= zms_rd_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= zms_rd_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'gray', label = 'Rizari-Daubert')
sns.lineplot(marker='', x= zms_ped_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= zms_ped_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'red', label = 'Pedersen')
sns.lineplot(marker='o', x= zms_kl_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= zms_kl_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'blue', label = 'kesler-Lee')
sns.lineplot(marker='', x= zms_sd_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= zms_sd_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= zms_brs_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= zms_brs_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='X', x = [8, 7.38, 0.8, 0.3, 0.1, 0.101], y = [26.37, 26.37, 2.7, 1.7, 0, 0], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test GOR sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='o', x= zms_rd_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= zms_rd_model.experiments.SEPARATORTEST_MOD.result.bo, color = 'gray', label = 'Rizari-Daubert')
sns.lineplot(marker='', x= zms_ped_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= zms_ped_model.experiments.SEPARATORTEST_MOD.result.bo, color = 'red', label = 'Pedersen')
sns.lineplot(marker='o', x= zms_kl_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= zms_kl_model.experiments.SEPARATORTEST_MOD.result.bo, color = 'blue', label = 'kesler-Lee')
sns.lineplot(marker='', x= zms_sd_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= zms_sd_model.experiments.SEPARATORTEST_MOD.result.bo, color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= zms_brs_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= zms_brs_model.experiments.SEPARATORTEST_MOD.result.bo, color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='X', x = [8, 7.38, 0.8, 0.3, 0.1, 0.101], y = [1.058, 1.059, 1.004, 1.002, 1, 1], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test GOR sensetivity to critial pressure')

In [ ]:
dle_res_view = DLEResultsViewer()
dle_res_view.view(zms_ped_model.experiments.SEPARATORTEST_MOD.result)

## DL

In [ ]:
zms_rd_model.experiments.DLE.calculate(7.38, 18, [6.3, 5.1, 3.9, 2.7, 1.5, 0.1])
zms_ped_model.experiments.DLE.calculate(7.38, 18, [6.3, 5.1, 3.9, 2.7, 1.5, 0.1])
zms_kl_model.experiments.DLE.calculate(7.38, 18, [6.3, 5.1, 3.9, 2.7, 1.5, 0.1])
zms_sd_model.experiments.DLE.calculate(7.38, 18, [6.3, 5.1, 3.9, 2.7, 1.5, 0.1])
zms_brs_model.experiments.DLE.calculate(7.38, 18, [6.3, 5.1, 3.9, 2.7, 1.5, 0.1])

In [ ]:
dle_res_view = DLEResultsViewer()
dle_res_view.view(zms_ped_model.experiments.DLE.result)

In [ ]:
zms_dle_pres_arr = [
8,
7.38,
6.3,
5.1,
3.9,
2.7,
1.5,
0.1,
0.1,
]

zms_dle_rs_arr = [
27.61,
27.61,
24.02,
19.76,
15.11,
10.16,
5.29,
0,
0
]

zms_dle_bo_arr = [
1.06,
1.061,
1.052,
1.042,
1.031,
1.021,
1.01,
0.999,
1,
]

In [ ]:
sns.lineplot(marker='o', x= zms_rd_model.experiments.DLE.result.pressure_arr, y= zms_rd_model.experiments.DLE.result.rs, color = 'gray', label = 'Rizari-Daubert')
#sns.lineplot(marker='', x= zms_ped_model.experiments.DLE.result.pressure_arr, y= zms_ped_model.experiments.DLE.result.rs, color = 'red', label = 'Pedersen')
sns.lineplot(marker='o', x= zms_kl_model.experiments.DLE.result.pressure_arr, y= zms_kl_model.experiments.DLE.result.rs, color = 'blue', label = 'kesler-Lee')
sns.lineplot(marker='', x= zms_sd_model.experiments.DLE.result.pressure_arr, y= zms_sd_model.experiments.DLE.result.rs, color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= zms_brs_model.experiments.DLE.result.pressure_arr, y= zms_brs_model.experiments.DLE.result.rs, color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='X', x = zms_dle_pres_arr, y = zms_dle_rs_arr, label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('DLE GOR sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='o', x= zms_rd_model.experiments.DLE.result.pressure_arr, y= zms_rd_model.experiments.DLE.result.bo, color = 'gray', label = 'Rizari-Daubert')
#sns.lineplot(marker='', x= zms_ped_model.experiments.DLE.result.pressure_arr, y= zms_ped_model.experiments.DLE.result.bo, color = 'red', label = 'Pedersen')
sns.lineplot(marker='o', x= zms_kl_model.experiments.DLE.result.pressure_arr, y= zms_kl_model.experiments.DLE.result.bo, color = 'blue', label = 'kesler-Lee')
sns.lineplot(marker='', x= zms_sd_model.experiments.DLE.result.pressure_arr, y= zms_sd_model.experiments.DLE.result.bo, color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= zms_brs_model.experiments.DLE.result.pressure_arr, y= zms_brs_model.experiments.DLE.result.bo, color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='X', x = zms_dle_pres_arr, y = zms_dle_bo_arr, label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('BO, sm3/sm3')
plt.title('DLE BO sensetivity to critial pressure')

## CCE

In [ ]:
zms_rd_model.experiments.CCE.calculate(8, 18, [18.15, 16.96, 15.18, 13.54, 11.1, 9.65])
zms_ped_model.experiments.CCE.calculate(8, 18, [18.15, 16.96, 15.18, 13.54, 11.1, 9.65])
zms_kl_model.experiments.CCE.calculate(8, 18, [18.15, 16.96, 15.18, 13.54, 11.1, 9.65])
zms_sd_model.experiments.CCE.calculate(8, 18, [18.15, 16.96, 15.18, 13.54, 11.1, 9.65])
zms_brs_model.experiments.CCE.calculate(8, 18, [18.15, 16.96, 15.18, 13.54, 11.1, 9.65])

In [ ]:
zms_cce_lden = [
0.9276,
0.9266,
0.9251,
0.9237,
0.9215,
0.9203,
0.9188,
]

zms_cce_pres = [
18.15,
16.96,
15.18,
13.54,
11.1,
9.65,
8,

]

zms_cce_v_vsat = [
0.989,
0.99,
0.992,
0.994,
0.996,
0.997,
0.999,

]

In [ ]:
sns.lineplot(marker='o', x= zms_rd_model.experiments.CCE.dataframe['Pressure'], y= zms_rd_model.experiments.CCE.dataframe['Liquid density'], color = 'gray', label = 'Rizari-Daubert')
#sns.lineplot(marker='', x= zms_ped_model.experiments.DLE.result.pressure_arr, y= zms_ped_model.experiments.DLE.result.rs, color = 'red', label = 'Pedersen')
sns.lineplot(marker='o', x= zms_kl_model.experiments.CCE.dataframe['Pressure'], y= zms_kl_model.experiments.CCE.dataframe['Liquid density'], color = 'blue', label = 'kesler-Lee')
sns.lineplot(marker='', x= zms_sd_model.experiments.CCE.dataframe['Pressure'], y= zms_sd_model.experiments.CCE.dataframe['Liquid density'], color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= zms_brs_model.experiments.CCE.dataframe['Pressure'], y= zms_brs_model.experiments.CCE.dataframe['Liquid density'], color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='X', x = zms_cce_pres, y = zms_cce_lden, label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('CCE density sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='o', x= zms_rd_model.experiments.CCE.dataframe['Pressure'], y= zms_rd_model.experiments.CCE.dataframe['V/Vsat'], color = 'gray', label = 'Rizari-Daubert')
#sns.lineplot(marker='', x= zms_ped_model.experiments.DLE.result.pressure_arr, y= zms_ped_model.experiments.DLE.result.rs, color = 'red', label = 'Pedersen')
sns.lineplot(marker='o', x= zms_kl_model.experiments.CCE.dataframe['Pressure'], y= zms_kl_model.experiments.CCE.dataframe['V/Vsat'], color = 'blue', label = 'kesler-Lee')
sns.lineplot(marker='', x= zms_sd_model.experiments.CCE.dataframe['Pressure'], y= zms_sd_model.experiments.CCE.dataframe['V/Vsat'], color = 'green', label = 'Sim-Daubert')
sns.lineplot(marker='', x= zms_brs_model.experiments.CCE.dataframe['Pressure'], y= zms_brs_model.experiments.CCE.dataframe['V/Vsat'], color = 'orange', label = 'Brusilovsky')
sns.lineplot(marker='X', x = zms_cce_pres, y = zms_cce_v_vsat, label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('V/Vsat, sm3/sm3')
plt.title('CCE V/Vsat sensetivity to critial pressure')

# NP 13comps

In [ ]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\np.xlsx')
np_dict = excel_loader.load(header=True, sheet='to_model')

### Для различных УРС

#### Расчет УРС АИ

In [ ]:
base_comp = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
model_ai = CompositionalModel(base_comp, eos = 'BRSEOS')

In [ ]:
base_comp.COMPOSITION_PROPERTIES

In [ ]:
conds = Conditions(5,50)
model_ai.flash(conds)

#### Расчет фазовой для уравнения АИ

In [ ]:
phase_env_ai = PhaseDiagram(base_comp, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_ai.calc_phase_diagram('BRSEOS')
phase_env_ai_data = phase_env_ai.get_phase_diagram_data()

#### Расчет фазовой для PR

In [ ]:
phase_env_pr = PhaseDiagram(base_comp, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_pr.calc_phase_diagram('PREOS')

In [ ]:
phase_env_pr_data = phase_env_pr.get_phase_diagram_data()

### Расчет сепаратор теста для различных УРС

In [ ]:
comp_mw_c13 = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
comp_mw_c13.edit_component_properties('C13', {'molar_mass' : 275})
comp_mw_c13.COMPOSITION_PROPERTIES

In [ ]:
model_ai = CompositionalModel(base_comp, eos = 'BRSEOS')
model_ai_mw = CompositionalModel(comp_mw_c13, eos = 'BRSEOS')
model_pr = CompositionalModel(base_comp, eos = 'PREOS')
model_srk = CompositionalModel(base_comp, eos = 'SRKEOS')
conds = Conditions(5,50)

In [ ]:
model_ai.flash(conds)
model_pr.flash(conds)
model_srk.flash(conds)

In [ ]:
model_ai.show_flashes

In [ ]:
model_pr.show_flashes

In [ ]:
model_srk.show_flashes

In [ ]:
model_ai.experiments.SEPARATORTEST_MOD.calculate(20, 70, [0.8, 0.5, 0.1], [20, 20, 20])
model_pr.experiments.SEPARATORTEST_MOD.calculate(20, 70, [0.8, 0.5, 0.1], [20, 20, 20])
model_srk.experiments.SEPARATORTEST_MOD.calculate(20, 70, [0.8, 0.5, 0.1], [20, 20, 20])
model_ai_mw.experiments.SEPARATORTEST_MOD.calculate(20, 70, [0.8, 0.5, 0.1], [20, 20, 20])

In [ ]:
sns.lineplot(marker='X', x= model_ai.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ai.experiments.SEPARATORTEST_MOD.result.rs, color = 'gray', label = 'Brusilovsky')
sns.lineplot(marker='', x= model_pr.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pr.experiments.SEPARATORTEST_MOD.result.rs, color = 'red', label = 'PR')
sns.lineplot(marker='', x= model_srk.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_srk.experiments.SEPARATORTEST_MOD.result.rs, color = 'blue', label = 'SRK')
sns.lineplot(marker='', x= model_ai_mw.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ai_mw.experiments.SEPARATORTEST_MOD.result.rs, color = 'black', label = 'BRS_MW')
# sns.lineplot(marker='X', x = [30, 21.2, 0.55, 0.16, 0], y = [158.85, 158.85, 13.33, 6.14, 0], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test GOR sensetivity to critial pressure')

#### Расчет фазовой для SRK

In [ ]:
phase_env_srk = PhaseDiagram(base_comp, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_srk.calc_phase_diagram('SRKEOS')

In [ ]:
phase_env_srk_data = phase_env_srk.get_phase_diagram_data()

#### Сравнение фазовых AI, SRK и PR

In [ ]:
import seaborn as sns

In [ ]:
sns.lineplot(marker='o',data = phase_env_ai_data, x= phase_env_ai_data['Temp'], y= phase_env_ai_data['Up'], color = 'blue', label = 'BRSEOS')
sns.lineplot(marker='o',data = phase_env_ai_data, x= phase_env_ai_data['Temp'], y= phase_env_ai_data['Low'], color = 'blue')
sns.lineplot(marker='o',data = phase_env_pr_data, x= phase_env_pr_data['Temp'], y= phase_env_pr_data['Up'], color = 'red', label = 'PREOS')
sns.lineplot(marker='o',data = phase_env_pr_data, x= phase_env_pr_data['Temp'], y= phase_env_pr_data['Low'], color = 'red')
sns.lineplot(marker='o',data = phase_env_srk_data, x= phase_env_srk_data['Temp'], y= phase_env_srk_data['Up'], color = 'green', label = 'SRKEOS')
sns.lineplot(marker='o',data = phase_env_srk_data, x= phase_env_srk_data['Temp'], y= phase_env_srk_data['Low'], color = 'green')

### Rizari_daubert

In [ ]:
np_comp_rizari_daubert = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'rizari_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_rd = PhaseDiagram(np_comp_rizari_daubert, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_rd.calc_phase_diagram('PREOS')

In [ ]:
np_data_rizari_daubert = phase_env_rd.get_phase_diagram_data()

### pedersen

In [ ]:
np_comp_pedersen = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_pd = PhaseDiagram(np_comp_pedersen, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_pd.calc_phase_diagram('PREOS')
np_data_pedersen = phase_env_pd.get_phase_diagram_data()

### Kesler-Lee

In [ ]:
np_comp_kesler_lee = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'kesler_lee',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_kl = PhaseDiagram(np_comp_kesler_lee, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_kl.calc_phase_diagram('PREOS')
np_data_kesler_lee = phase_env_kl.get_phase_diagram_data()

### Sim_Daubert

In [ ]:
np_comp_sim_daubert = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'sim_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_sd = PhaseDiagram(np_comp_sim_daubert, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_sd.calc_phase_diagram('PREOS')
np_data_sim_d = phase_env_sd.get_phase_diagram_data()

### Standing

In [ ]:
np_comp_standing = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'standing',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_std = PhaseDiagram(np_comp_standing, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_std.calc_phase_diagram('PREOS')
np_data_std = phase_env_std.get_phase_diagram_data()

### Twu

In [ ]:
np_comp_standing.COMPOSITION

In [ ]:
np_comp_twu = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'twu',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_twu = PhaseDiagram(np_comp_twu, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_twu.calc_phase_diagram('PREOS')
np_data_twu = phase_env_twu.get_phase_diagram_data()

### BRS

In [ ]:
np_comp_brs = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pc_from_eos',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_brs = PhaseDiagram(np_comp_brs, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_brs.calc_phase_diagram('PREOS')
np_data_brs = phase_env_brs.get_phase_diagram_data()

## Свод график

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
sns.lineplot(marker='o',data = np_data_rizari_daubert, x= np_data_rizari_daubert['Temp'], y= np_data_rizari_daubert['Up'], color = 'blue', label = 'Rizari-Daubert')
sns.lineplot(marker='o',data = np_data_rizari_daubert, x= np_data_rizari_daubert['Temp'], y= np_data_rizari_daubert['Low'], color = 'blue')
sns.lineplot(marker='o',data = np_data_pedersen, x= np_data_pedersen['Temp'], y= np_data_pedersen['Up'], color = 'red', label = 'Pedersen')
sns.lineplot(marker='o',data = np_data_pedersen, x= np_data_pedersen['Temp'], y= np_data_pedersen['Low'], color = 'red')
sns.lineplot(marker='o',data = np_data_kesler_lee, x= np_data_kesler_lee['Temp'], y= np_data_kesler_lee['Up'], color = 'green', label = 'Kesler-Lee')
sns.lineplot(marker='o',data = np_data_kesler_lee, x= np_data_kesler_lee['Temp'], y= np_data_kesler_lee['Low'], color = 'green')
sns.lineplot(marker='o',data = np_data_sim_d, x= np_data_sim_d['Temp'], y= np_data_sim_d['Up'], color = 'gray', label = 'Sim-Daubert')
sns.lineplot(marker='o',data = np_data_sim_d, x= np_data_sim_d['Temp'], y= np_data_sim_d['Low'], color = 'gray')
sns.lineplot(marker='o',data = np_data_brs, x= np_data_brs['Temp'], y= np_data_brs['Up'], color = 'orange', label = 'Brusilovskiy')
sns.lineplot(marker='o',data = np_data_brs, x= np_data_brs['Temp'], y= np_data_brs['Low'], color = 'orange')
sns.lineplot(marker='o',data = np_data_twu, x= np_data_twu['Temp'], y= np_data_twu['Up'], color = 'black', label = 'Twu')
sns.lineplot(marker='o',data = np_data_twu, x= np_data_twu['Temp'], y= np_data_twu['Low'], color = 'black')
# sns.lineplot(marker='o',data = np_data_std, x= np_data_std['Temp'], y= np_data_std['Up'], color = 'gray', label = 'Standing')
# sns.lineplot(marker='o',data = np_data_std, x= np_data_std['Temp'], y= np_data_std['Low'], color = 'gray')
sns.scatterplot(x=[57.7], y = [11.7], label = 'Psat_fact', marker = 'x')
plt.title('Novoport phase envelope')
plt.ylabel('Pressure, MPa')
plt.xlabel('Temp, C')

# NP36 SHLM

In [ ]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\np.xlsx')
np_dict_36 = excel_loader.load(header=True, sheet='to_model_36comps_shlm')

In [ ]:
base_comp_36 = Composition(np_dict_36)
base_comp_36.edit_component_properties('C36', {'molar_mass':611.14})

In [ ]:
model_ai_36 = CompositionalModel(base_comp_36, eos = 'BRSEOS')
model_pr_36 = CompositionalModel(base_comp_36, eos = 'PREOS')
model_srk_36 = CompositionalModel(base_comp_36, eos = 'SRKEOS')

In [ ]:
model_pr_36.saturation_pressure(50)

In [ ]:
model_ai_36.experiments.SEPARATORTEST_MOD.calculate(18.7, 64.8, [0.8, 0.5], [20, 20])
model_pr_36.experiments.SEPARATORTEST_MOD.calculate(18.7, 64.8, [0.8, 0.5], [20, 20, 20])
model_srk_36.experiments.SEPARATORTEST_MOD.calculate(18.7, 64.8, [0.8, 0.5], [20, 20, 20])

In [ ]:
dle_res_view = DLEResultsViewer()
dle_res_view.view(model_ai_36.experiments.SEPARATORTEST_MOD.result)

In [ ]:
sns.lineplot(marker='X', x= model_ai_36.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ai_36.experiments.SEPARATORTEST_MOD.result.rs, color = 'gray', label = 'Brusilovsky')
sns.lineplot(marker='', x= model_pr_36.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pr_36.experiments.SEPARATORTEST_MOD.result.rs, color = 'red', label = 'PR')
sns.lineplot(marker='', x= model_srk_36.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_srk_36.experiments.SEPARATORTEST_MOD.result.rs, color = 'blue', label = 'SRK')
#sns.lineplot(marker='', x= model_ai_mw.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ai_mw.experiments.SEPARATORTEST_MOD.result.rs, color = 'blue', label = 'BRS_MW')
# sns.lineplot(marker='X', x = [30, 21.2, 0.55, 0.16, 0], y = [158.85, 158.85, 13.33, 6.14, 0], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test GOR sensetivity to critial pressure')

## ST SEP 6.01

In [ ]:
np_st_sep_pres_arr = [
18.7,
18.03,
0.101325
]

np_st_sep_rs = [
116.6,
116.6,
0
]

np_st_sep_bo = [
1.327,
1.329,
1
]

In [ ]:
model_ai_36.experiments.STANDARDSEPARATION.calculate(18.7, 64)
model_pr_36.experiments.STANDARDSEPARATION.calculate(18.7, 64)
model_srk_36.experiments.STANDARDSEPARATION.calculate(18.7, 64)

In [ ]:
np_ai_rs = [model_ai_36.experiments.STANDARDSEPARATION._result.rs, model_ai_36.experiments.STANDARDSEPARATION._result.rs, 0]
np_pr_rs = [model_pr_36.experiments.STANDARDSEPARATION._result.rs, model_pr_36.experiments.STANDARDSEPARATION._result.rs, 0]
np_srk_rs = [model_srk_36.experiments.STANDARDSEPARATION._result.rs, model_srk_36.experiments.STANDARDSEPARATION._result.rs, 0]

In [ ]:
np_ai_bo = [model_ai_36.experiments.STANDARDSEPARATION._result.bo_p_res, model_ai_36.experiments.STANDARDSEPARATION._result.bo_p_sat, 1]
np_pr_bo = [model_pr_36.experiments.STANDARDSEPARATION._result.bo_p_res, model_pr_36.experiments.STANDARDSEPARATION._result.bo_p_sat, 1]
np_srk_bo = [model_srk_36.experiments.STANDARDSEPARATION._result.bo_p_res, model_srk_36.experiments.STANDARDSEPARATION._result.bo_p_sat, 1]

In [ ]:
sns.lineplot(marker='X', x= np_st_sep_pres_arr, y= np_ai_bo, color = 'gray', label = 'Brusilovsky')
sns.lineplot(marker='', x= np_st_sep_pres_arr, y= np_pr_bo, color = 'red', label = 'PR')
sns.lineplot(marker='', x= np_st_sep_pres_arr, y= np_srk_bo, color = 'blue', label = 'SRK')
sns.lineplot(marker='o', x= np_st_sep_pres_arr, y= np_st_sep_bo, color = 'black', label = 'LAB')
#sns.lineplot(marker='', x= model_ai_mw.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ai_mw.experiments.SEPARATORTEST_MOD.result.rs, color = 'blue', label = 'BRS_MW')
# sns.lineplot(marker='X', x = [30, 21.2, 0.55, 0.16, 0], y = [158.85, 158.85, 13.33, 6.14, 0], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test GOR sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='X', x= np_st_sep_pres_arr, y= np_ai_rs, color = 'gray', label = 'Brusilovsky')
sns.lineplot(marker='', x= np_st_sep_pres_arr, y= np_pr_rs, color = 'red', label = 'PR')
sns.lineplot(marker='', x= np_st_sep_pres_arr, y= np_srk_rs, color = 'blue', label = 'SRK')
sns.lineplot(marker='o', x= np_st_sep_pres_arr, y= np_st_sep_rs, color = 'black', label = 'LAB')
#sns.lineplot(marker='', x= model_ai_mw.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ai_mw.experiments.SEPARATORTEST_MOD.result.rs, color = 'blue', label = 'BRS_MW')
# sns.lineplot(marker='X', x = [30, 21.2, 0.55, 0.16, 0], y = [158.85, 158.85, 13.33, 6.14, 0], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test GOR sensetivity to critial pressure')

### Добавляем бинарники АИ

# YAMB

In [2]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\yamb.xlsx')
yamb_dict = excel_loader.load(header=True, sheet='to_model')

In [3]:
yamb_comp = Composition(yamb_dict)

In [4]:
yamb_comp.edit_component_properties('C36', {'molar_mass': 598.8})

In [5]:
yamb_model = CompositionalModel(yamb_comp, eos= 'PREOS')

In [6]:
conds = Conditions(26,50)

In [7]:
yamb_model.flash(conds)

In [8]:
yamb_model._flash_results

{'TwoPhaseFlash_26_50.0': TwoPhaseFlashResults(temperature=323.14, pressure=26, stable=False, EOS='PREOS', Fv=0.07679822236968903, Fl=0.923201777630311, Ki={'CO2': 0.9087789464670153, 'N2': 1.698461106506402, 'C1': 1.3115966187811763, 'C2': 0.8814104048520054, 'C3': 0.7071460817240308, 'iC4': 0.590782356073321, 'nC4': 0.5214456495851656, 'iC5': 0.4272166051103364, 'nC5': 0.44640291054109815, 'C6': 0.3507364868330176, 'C7': 0.2945636941719341, 'C8': 0.24943235479025033, 'C9': 0.2099718019225712, 'C10': 0.179054084626916, 'C11': 0.15459235360005683, 'C12': 0.132814293224061, 'C13': 0.1136052356972475, 'C14': 0.09678849981622388, 'C15': 0.08162506569936451, 'C16': 0.0700602534916095, 'C17': 0.05942655196995559, 'C18': 0.052164851025622426, 'C19': 0.04593930869680771, 'C20': 0.039787826299622936, 'C21': 0.03419102286338221, 'C22': 0.02948867793882368, 'C23': 0.02524397897209248, 'C24': 0.021750540579328882, 'C25': 0.018610130301869865, 'C26': 0.015784402253851356, 'C27': 0.013275363975005726, 'C28': 0.011248615540622597, 'C29': 0.009624859280619244, 'C30': 0.008336003837594998, 'C31': 0.007055830728644723, 'C32': 0.0060419478922612265, 'C33': 0.005143714965248531, 'C34': 0.004435064461043273, 'C35': 0.0037308904483875087, 'C36': 0.0031796923225918903}, liquid_composition={'CO2': 0.0030312356693279665, 'N2': 0.0012907627486538579, 'C1': 0.6460109158758217, 'C2': 0.05637341923001048, 'C3': 0.04790747065002285, 'iC4': 0.011057506325866811, 'nC4': 0.02573584702620314, 'iC5': 0.009361814484419785, 'nC5': 0.01197930334461259, 'C6': 0.027901218469822086, 'C7': 0.028208215453254915, 'C8': 0.02217841392209615, 'C9': 0.012093761930003253, 'C10': 0.01392812937685801, 'C11': 0.010266564990661848, 'C12': 0.008710076466208222, 'C13': 0.008230263167160558, 'C14': 0.006651372718997453, 'C15': 0.006218594767864489, 'C16': 0.004759944371701328, 'C17': 0.0041820906806516464, 'C18': 0.0038934092591408056, 'C19': 0.0033450957154279397, 'C20': 0.0027854028120917577, 'C21': 0.0025058661370171084, 'C22': 0.0021610723843459223, 'C23': 0.001956459649130939, 'C24': 0.0017407810873501207, 'C25': 0.0015681931451491285, 'C26': 0.001395478661759675, 'C27': 0.001287570409212922, 'C28': 0.0011687481278752597, 'C29': 0.0011147898578575312, 'C30': 0.0010283144011659973, 'C31': 0.0009418197324337652, 'C32': 0.0008877669934514155, 'C33': 0.0007145975341817766, 'C34': 0.0007254675178451518, 'C35': 0.0006497104487420013, 'C36': 0.004082534455602967}, vapour_composition={'CO2': 0.002754723158065107, 'N2': 0.0021923103263158765, 'C1': 0.8473057329584587, 'C2': 0.049688118266415365, 'C3': 0.03387758015547267, 'iC4': 0.006532579639491245, 'nC4': 0.013419845470202947, 'iC5': 0.003999522601706595, 'nC5': 0.005347595879289772, 'C6': 0.0097859753444659, 'C7': 0.008309116149908606, 'C8': 0.005532014010101314, 'C9': 0.0025393489844653754, 'C10': 0.0024938884561385684, 'C11': 0.0015871324452943606, 'C12': 0.001156822649786972, 'C13': 0.00093500098695565, 'C14': 0.0006437763871903215, 'C15': 0.0005075932064846632, 'C16': 0.00033348290928735495, 'C17': 0.000248527229176812, 'C18': 0.0002030991139848591, 'C19': 0.00015367138469141295, 'C20': 0.00011082512326198812, 'C21': 8.56781263833272e-05, 'C22': 6.372716754446269e-05, 'C23': 4.938882624240886e-05, 'C24': 3.786292968013706e-05, 'C25': 2.9184278769724404e-05, 'C26': 2.202679653388089e-05, 'C27': 1.7092965825748603e-05, 'C28': 1.3146798354291212e-05, 'C29': 1.0729695509340267e-05, 'C30': 8.572032794373957e-06, 'C31': 6.645320608950111e-06, 'C32': 5.3638419149028655e-06, 'C33': 3.6756860307005028e-06, 'C34': 3.217495206036309e-06, 'C35': 2.4239985074290944e-06, 'C36': 1.2981203465197618e-05}, liquid_z=0.9026222227174463, vapour_z=0.8022476203944062, vapour_molecular_mass=22.663427980211768, liquid_molecular_mass=49.66783863438131, vapour_volume=6.36323557508126, liquid_volume=86.06390553037039, vapour_molar_volume=82.85654770041556, liquid_molar_volume=93.22328835986494, vapour_density=0.27352609551336765, liquid_density=0.5327835941878726, vapour_viscosity=0.03802263165579141, liquid_viscosity=0.1363485115493565)}

In [17]:
yamb_model.saturation_pressure(50)

SATURATION PRESSURE CALCULATION
=====
CALCULATED SATURATION PRESSURE: 300.25 bar
TEMPERATURE: 50 C

AttributeError: 'SaturationPressureCalculation' object has no attribute 'get_debug_info'

# POKAMASS - MPSR 3005

In [10]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\pokamass.xlsx')
pokamass_dict = excel_loader.load(header=True, sheet='to_model')

In [11]:
pokamass_comp = Composition(pokamass_dict)

In [12]:
pokamass_comp.COMPOSITION_PROPERTIES

,key_0,0,molar_mass,gamma,Tb,critical_pressure,critical_temperature,acentric_factor,shift_parameter,critical_volume,bip,c5_plus_flag
0,N2,0.00076,28.013,0.4700,77.39,3.394000,126.190000,0.040000,-0.192700,0.090100,"{'CO2': 0, 'N2': 0, 'C1': 0.003, 'C2': 0.011, ...",0
1,CO2,0.00535,44.010,0.5000,194.67,7.387000,304.690000,0.225000,-0.081700,1.505735,"{'CO2': 0, 'N2': 0, 'C1': 0.004, 'C2': 0.009, ...",0
2,C1,0.31554,16.043,0.3300,111.67,4.604000,190.600000,0.013000,-0.159500,1.585828,"{'CO2': 0.004, 'N2': 0.003, 'C1': 0, 'C2': 0.0...",0
3,C2,0.03334,30.070,0.4500,184.56,4.884000,305.420000,0.099000,-0.113400,2.370730,"{'CO2': 0.009, 'N2': 0.011, 'C1': 0.024, 'C2':...",0
4,C3,0.05537,44.097,0.5077,231.11,4.246000,369.790000,0.152000,-0.086300,3.251740,"{'CO2': 0, 'N2': 0, 'C1': 0.004, 'C2': 0.009, ...",0
5,iC4,0.01312,58.124,0.5613,261.44,3.648000,408.090000,0.185000,-0.084400,4.212855,"{'CO2': 0.008, 'N2': 0.01, 'C1': 0.023, 'C2': ...",0
6,nC4,0.03079,58.124,0.5844,272.67,3.797000,425.190000,0.201000,-0.094000,4.084708,"{'CO2': 0.023, 'N2': 0.026, 'C1': 0.045, 'C2':...",0
7,iC5,0.01193,72.151,0.6274,301.00,3.389000,460.390000,0.227000,-0.060800,4.901640,"{'CO2': 0.04, 'N2': 0.044, 'C1': 0.067, 'C2': ...",0
8,nC5,0.01581,72.151,0.6301,309.22,3.370000,469.590000,0.251000,-0.039000,4.869612,"{'CO2': 0, 'N2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",0
9,C6,0.02771,86.178,0.6900,337.05,3.104000,507.500000,0.252000,-0.008000,5.926800,"{'CO2': 0.05, 'N2': 0.054, 'C1': 0.042, 'C2': ...",1
10,C7,0.04288,96.000,0.7270,365.05,3.133670,542.425284,0.314414,-0.039968,6.129490,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
11,C8,0.04520,107.000,0.7490,389.85,2.884574,570.548990,0.344631,-0.014077,6.781567,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
12,C9,0.03730,121.000,0.7680,415.35,2.640528,598.101705,0.379097,0.014491,7.657889,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
13,C10,0.03373,134.000,0.7820,438.95,2.423211,622.207636,0.415144,0.037589,8.488891,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
14,C11,0.02981,147.000,0.7930,460.35,2.242123,643.211673,0.450955,0.058077,9.338598,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
15,C12,0.02682,161.000,0.8040,481.45,2.087046,663.637780,0.487819,0.077782,10.255789,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
16,C13,0.02463,175.000,0.8150,500.35,1.970393,682.052389,0.520877,0.095481,11.166838,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
17,C14,0.02178,190.000,0.8260,519.55,1.863135,700.529768,0.555636,0.112604,12.144593,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
18,C15,0.02024,206.000,0.8360,539.15,1.758650,718.830726,0.593761,0.129122,13.201298,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
19,C16,0.01722,222.000,0.8430,556.15,1.668796,734.012976,0.630294,0.144131,14.292288,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
20,C17,0.01609,237.000,0.8510,573.15,1.591040,749.405879,0.666568,0.157037,15.293310,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
21,C18,0.01465,251.000,0.8560,586.15,1.531296,760.717895,0.696929,0.168206,16.260985,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
22,C19,0.01360,263.000,0.8610,598.15,1.481066,771.235587,0.725047,0.177185,17.079066,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
23,C20,0.01163,275.000,0.8660,611.15,1.428287,782.425100,0.757071,0.185673,17.895843,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
24,C21,0.01046,291.000,0.8710,624.15,1.378724,793.557111,0.790014,0.196305,19.011332,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
25,C22,0.00966,305.000,0.8760,636.15,1.336963,803.926774,0.820451,0.205034,19.975967,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
26,C23,0.00873,318.000,0.8810,648.15,1.297436,814.257812,0.851631,0.212708,20.863771,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
27,C24,0.00798,331.000,0.8850,659.15,1.261099,823.477599,0.882248,0.220005,21.769212,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
28,C25,0.00723,345.000,0.8880,670.15,1.223312,832.285994,0.916123,0.227478,22.770170,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
29,C26,0.00674,359.000,0.8920,681.15,1.190460,841.439317,0.948481,0.234587,23.751121,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
30,C27,0.00609,374.000,0.8960,692.15,1.159135,850.564319,0.981696,0.241834,24.807668,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
31,C28,0.00577,388.000,0.8990,702.15,1.130045,858.588807,1.014481,0.248281,25.810010,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
32,C29,0.00527,402.000,0.9020,711.15,1.105761,865.907445,1.043889,0.254448,26.812887,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
33,C30,0.00496,416.000,0.9050,719.15,1.085856,872.529981,1.069591,0.260356,27.816129,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
34,C31,0.00439,430.000,0.9090,728.15,1.065922,880.215310,1.097095,0.266024,28.794417,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
35,C32,0.00404,444.000,0.9120,736.15,1.047301,886.815764,1.123802,0.271469,29.797136,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
36,C33,0.00355,458.000,0.9150,744.15,1.029260,893.405930,1.151036,0.276706,30.799784,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
37,C34,0.00304,472.000,0.9170,751.15,1.012330,898.911351,1.177540,0.281750,31.829751,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
38,C35,0.00278,486.000,0.9200,759.15,0.995345,905.482109,1.205887,0.286612,32.832661,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
39,C36,0.04402,500.000,0.9220,766.15,0.979363,910.968559,1.233555,0.291305,33.864255,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1

In [13]:
pokamass_comp.edit_component_properties('C36', {'molar_mass': 543.2})

In [14]:
pokamass_comp.COMPOSITION_PROPERTIES

,key_0,0,molar_mass,gamma,Tb,critical_pressure,critical_temperature,acentric_factor,shift_parameter,critical_volume,bip,c5_plus_flag
0,N2,0.00076,28.013,0.4700,77.39,3.394000,126.190000,0.040000,-0.192700,0.090100,"{'CO2': 0, 'N2': 0, 'C1': 0.003, 'C2': 0.011, ...",0
1,CO2,0.00535,44.010,0.5000,194.67,7.387000,304.690000,0.225000,-0.081700,1.505735,"{'CO2': 0, 'N2': 0, 'C1': 0.004, 'C2': 0.009, ...",0
2,C1,0.31554,16.043,0.3300,111.67,4.604000,190.600000,0.013000,-0.159500,1.585828,"{'CO2': 0.004, 'N2': 0.003, 'C1': 0, 'C2': 0.0...",0
3,C2,0.03334,30.070,0.4500,184.56,4.884000,305.420000,0.099000,-0.113400,2.370730,"{'CO2': 0.009, 'N2': 0.011, 'C1': 0.024, 'C2':...",0
4,C3,0.05537,44.097,0.5077,231.11,4.246000,369.790000,0.152000,-0.086300,3.251740,"{'CO2': 0, 'N2': 0, 'C1': 0.004, 'C2': 0.009, ...",0
5,iC4,0.01312,58.124,0.5613,261.44,3.648000,408.090000,0.185000,-0.084400,4.212855,"{'CO2': 0.008, 'N2': 0.01, 'C1': 0.023, 'C2': ...",0
6,nC4,0.03079,58.124,0.5844,272.67,3.797000,425.190000,0.201000,-0.094000,4.084708,"{'CO2': 0.023, 'N2': 0.026, 'C1': 0.045, 'C2':...",0
7,iC5,0.01193,72.151,0.6274,301.00,3.389000,460.390000,0.227000,-0.060800,4.901640,"{'CO2': 0.04, 'N2': 0.044, 'C1': 0.067, 'C2': ...",0
8,nC5,0.01581,72.151,0.6301,309.22,3.370000,469.590000,0.251000,-0.039000,4.869612,"{'CO2': 0, 'N2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",0
9,C6,0.02771,86.178,0.6900,337.05,3.104000,507.500000,0.252000,-0.008000,5.926800,"{'CO2': 0.05, 'N2': 0.054, 'C1': 0.042, 'C2': ...",1
10,C7,0.04288,96.000,0.7270,365.05,3.133670,542.425284,0.314414,-0.039968,6.129490,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
11,C8,0.04520,107.000,0.7490,389.85,2.884574,570.548990,0.344631,-0.014077,6.781567,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
12,C9,0.03730,121.000,0.7680,415.35,2.640528,598.101705,0.379097,0.014491,7.657889,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
13,C10,0.03373,134.000,0.7820,438.95,2.423211,622.207636,0.415144,0.037589,8.488891,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
14,C11,0.02981,147.000,0.7930,460.35,2.242123,643.211673,0.450955,0.058077,9.338598,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
15,C12,0.02682,161.000,0.8040,481.45,2.087046,663.637780,0.487819,0.077782,10.255789,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
16,C13,0.02463,175.000,0.8150,500.35,1.970393,682.052389,0.520877,0.095481,11.166838,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
17,C14,0.02178,190.000,0.8260,519.55,1.863135,700.529768,0.555636,0.112604,12.144593,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
18,C15,0.02024,206.000,0.8360,539.15,1.758650,718.830726,0.593761,0.129122,13.201298,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
19,C16,0.01722,222.000,0.8430,556.15,1.668796,734.012976,0.630294,0.144131,14.292288,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
20,C17,0.01609,237.000,0.8510,573.15,1.591040,749.405879,0.666568,0.157037,15.293310,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
21,C18,0.01465,251.000,0.8560,586.15,1.531296,760.717895,0.696929,0.168206,16.260985,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
22,C19,0.01360,263.000,0.8610,598.15,1.481066,771.235587,0.725047,0.177185,17.079066,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
23,C20,0.01163,275.000,0.8660,611.15,1.428287,782.425100,0.757071,0.185673,17.895843,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
24,C21,0.01046,291.000,0.8710,624.15,1.378724,793.557111,0.790014,0.196305,19.011332,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
25,C22,0.00966,305.000,0.8760,636.15,1.336963,803.926774,0.820451,0.205034,19.975967,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
26,C23,0.00873,318.000,0.8810,648.15,1.297436,814.257812,0.851631,0.212708,20.863771,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
27,C24,0.00798,331.000,0.8850,659.15,1.261099,823.477599,0.882248,0.220005,21.769212,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
28,C25,0.00723,345.000,0.8880,670.15,1.223312,832.285994,0.916123,0.227478,22.770170,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
29,C26,0.00674,359.000,0.8920,681.15,1.190460,841.439317,0.948481,0.234587,23.751121,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
30,C27,0.00609,374.000,0.8960,692.15,1.159135,850.564319,0.981696,0.241834,24.807668,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
31,C28,0.00577,388.000,0.8990,702.15,1.130045,858.588807,1.014481,0.248281,25.810010,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
32,C29,0.00527,402.000,0.9020,711.15,1.105761,865.907445,1.043889,0.254448,26.812887,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
33,C30,0.00496,416.000,0.9050,719.15,1.085856,872.529981,1.069591,0.260356,27.816129,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
34,C31,0.00439,430.000,0.9090,728.15,1.065922,880.215310,1.097095,0.266024,28.794417,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
35,C32,0.00404,444.000,0.9120,736.15,1.047301,886.815764,1.123802,0.271469,29.797136,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
36,C33,0.00355,458.000,0.9150,744.15,1.029260,893.405930,1.151036,0.276706,30.799784,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
37,C34,0.00304,472.000,0.9170,751.15,1.012330,898.911351,1.177540,0.281750,31.829751,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
38,C35,0.00278,486.000,0.9200,759.15,0.995345,905.482109,1.205887,0.286612,32.832661,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
39,C36,0.04402,543.200,0.9220,766.15,0.979363,910.968559,1.233555,0.304823,37.250298,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1

## SAT P

In [15]:
pokam_model = CompositionalModel(pokamass_comp, eos = 'PREOS')

In [16]:
pokam_model.saturation_pressure(150)

SATURATION PRESSURE CALCULATION
=====
CALCULATED SATURATION PRESSURE: 131.33740234375 bar
TEMPERATURE: 150 C

AttributeError: 'SaturationPressureCalculation' object has no attribute 'get_debug_info'

## PHASE ENV EOS

In [ ]:
phase_env_pokamass_pr = PhaseDiagram(pokamass_comp, p_max=30, t_max= 650, t_min=0, t_step=10)
phase_env_pokamass_pr.calc_phase_diagram('PREOS')
phase_env_pokamass_pr_data = phase_env_pokamass_pr.get_phase_diagram_data()

In [ ]:
phase_env_pokamass_srk = PhaseDiagram(pokamass_comp, p_max=30, t_max= 650, t_min=0, t_step=10)
phase_env_pokamass_srk.calc_phase_diagram('SRKEOS')
phase_env_pokamass_srk_data = phase_env_pokamass_srk.get_phase_diagram_data()

In [ ]:
phase_env_pokamass_brs = PhaseDiagram(pokamass_comp, p_max=30, t_max= 650, t_min=0, t_step=10)
phase_env_pokamass_brs.calc_phase_diagram('BRSEOS')
phase_env_pokamass_brs_data = phase_env_pokamass_brs.get_phase_diagram_data()

In [ ]:
sns.lineplot(marker='o',data = phase_env_pokamass_pr_data, x= phase_env_pokamass_pr_data['Temp'], y= phase_env_pokamass_pr_data['Up'], color = 'blue', label = 'PR')
sns.lineplot(marker='o',data = phase_env_pokamass_pr_data, x= phase_env_pokamass_pr_data['Temp'], y= phase_env_pokamass_pr_data['Low'], color = 'blue')
sns.lineplot(marker='',data = phase_env_pokamass_srk_data, x= phase_env_pokamass_srk_data['Temp'], y= phase_env_pokamass_srk_data['Up'], color = 'red', label = 'SRK')
sns.lineplot(marker='',data = phase_env_pokamass_srk_data, x= phase_env_pokamass_srk_data['Temp'], y= phase_env_pokamass_srk_data['Low'], color = 'red')
sns.lineplot(marker='X',data = phase_env_pokamass_brs_data, x= phase_env_pokamass_brs_data['Temp'], y= phase_env_pokamass_brs_data['Up'], color = 'gray', label = 'BRS')
sns.lineplot(marker='X',data = phase_env_pokamass_brs_data, x= phase_env_pokamass_brs_data['Temp'], y= phase_env_pokamass_brs_data['Low'], color = 'gray')

sns.scatterplot(x=[87.6], y = [11.87], color = 'green', label = 'Psat_fact')
plt.title('Pokamass Phase Envelope')
plt.xlabel('Temperature, C')
plt.ylabel('Pressure, MPa')
plt.ylim((0, 15))

# IGN #9

In [ ]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\ignyalin.xlsx')
ign_dict = excel_loader.load(header=True, sheet='to_model')

In [ ]:
ign_comp = Composition(ign_dict)

In [ ]:
ign_comp.COMPOSITION_PROPERTIES

In [ ]:
ign_comp.edit_component_properties('C36', {'molar_mass': 530.2})

In [ ]:
ign_comp.COMPOSITION_PROPERTIES

## PHASE ENV

In [ ]:
phase_env_ign_pr = PhaseDiagram(ign_comp, p_max=30, t_max= 650, t_min=0, t_step=10)
phase_env_ign_pr.calc_phase_diagram('PREOS')
phase_env_ign_pr_data = phase_env_ign_pr.get_phase_diagram_data()

In [ ]:
phase_env_ign_srk = PhaseDiagram(ign_comp, p_max=30, t_max= 650, t_min=0, t_step=10)
phase_env_ign_srk.calc_phase_diagram('SRKEOS')
phase_env_ign_srk_data = phase_env_ign_srk.get_phase_diagram_data()

In [ ]:
phase_env_ign_brs = PhaseDiagram(ign_comp, p_max=30, t_max= 650, t_min=0, t_step=10)
phase_env_ign_brs.calc_phase_diagram('BRSEOS')
phase_env_ign_brs_data = phase_env_ign_brs.get_phase_diagram_data()

In [ ]:
sns.lineplot(marker='',data = phase_env_ign_pr_data, x= phase_env_ign_pr_data['Temp'], y= phase_env_ign_pr_data['Up'], color = 'blue', label = 'PR')
sns.lineplot(marker='',data = phase_env_ign_pr_data, x= phase_env_ign_pr_data['Temp'], y= phase_env_ign_pr_data['Low'], color = 'blue')
sns.lineplot(marker='',data = phase_env_ign_srk_data, x= phase_env_ign_srk_data['Temp'], y= phase_env_ign_srk_data['Up'], color = 'red', label = 'SRK')
sns.lineplot(marker='',data = phase_env_ign_srk_data, x= phase_env_ign_srk_data['Temp'], y= phase_env_ign_srk_data['Low'], color = 'red')
sns.lineplot(marker='X',data = phase_env_ign_brs_data, x= phase_env_ign_brs_data['Temp'], y= phase_env_ign_brs_data['Up'], color = 'gray', label = 'BRS')
sns.lineplot(marker='X',data = phase_env_ign_brs_data, x= phase_env_ign_brs_data['Temp'], y= phase_env_ign_brs_data['Low'], color = 'gray')

sns.scatterplot(x=[17.9], y = [15.6], color = 'green', label = 'Psat_fact')
plt.title('Ign Phase Envelope')
plt.xlabel('Temperature, C')
plt.ylabel('Pressure, MPa')

## SAT P

In [ ]:
ign_base_model = CompositionalModel(ign_comp, eos= 'PREOS')

In [ ]:
ign_base_model.saturation_pressure(10)

# BOVAN - NONE

# Чувствительность к параметрам расчета

In [ ]:
conds = Conditions(5,30)

## Базовый состав

In [ ]:
# import os


# notebook_dir = os.getcwd()
# excel_path = os.path.join(notebook_dir, "diss", "prrzlm.xlsx")
# excel_path_str = f'{str(excel_path)}'
# print(excel_path_str)

excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\prrzlm_mdt.xlsx')
przlm_dict = excel_loader.load(header=True, sheet='to_model')

In [ ]:
base_composition = Composition(przlm_dict)
base_composition.edit_component_properties('C30', {'molar_mass':727.35})
base_model = CompositionalModel(base_composition)
base_model.flash(conds)

In [ ]:
base_flash_results = base_model._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
base_composition.COMPOSITION_PROPERTIES

In [ ]:
base_composition._composition_data

In [ ]:
base_sat_p = base_model.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_base = PhaseDiagram(base_composition, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_base.calc_phase_diagram('PREOS')
phase_env_base_data = phase_env_base.get_phase_diagram_data()

Выгрузка свойств

In [ ]:
base_flash_dict = {'Fv':base_flash_results.Fv,
                   'z_vap': base_flash_results.vapour_z,
                   'z_liquid':base_flash_results.liquid_z,
                   'density_liquid':base_flash_results.liquid_density,
                   'density_vapour':base_flash_results.vapour_density,
                   'Psat' : base_sat_p}

## Чувствительность к Рс

### Обвязка для варьирования свойства + 20%

In [ ]:
pc_120_dict = {}
base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_pc120 = Composition(przlm_dict)
for component in composition_pc120.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        pc_120_dict[component] = composition_pc120.COMPOSITION_PROPERTIES[composition_pc120.COMPOSITION_PROPERTIES['key_0'] == component]['critical_pressure'].iloc[0]
    else:
        pc_120_dict[component] = composition_pc120.COMPOSITION_PROPERTIES[composition_pc120.COMPOSITION_PROPERTIES['key_0'] == component]['critical_pressure'].iloc[0] * 1.2
print(pc_120_dict)
composition_pc120.set_property_dict('critical_pressure', pc_120_dict)

In [ ]:
composition_pc120.COMPOSITION_PROPERTIES

In [ ]:
model_pc120 = CompositionalModel(composition_pc120)
model_pc120.flash(conds)

In [ ]:
pc120_sat_p = model_pc120.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_pc120 = PhaseDiagram(composition_pc120, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_pc120.calc_phase_diagram('PREOS')
phase_env_pc120_data = phase_env_pc120.get_phase_diagram_data()

In [ ]:
pc120_flash_results = model_pc120._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
pc120_flash_dict = {'Fv':pc120_flash_results.Fv,
                   'z_vap': pc120_flash_results.vapour_z,
                   'z_liquid':pc120_flash_results.liquid_z,
                   'density_liquid':pc120_flash_results.liquid_density,
                   'density_vapour':pc120_flash_results.vapour_density,
                   'Psat' : pc120_sat_p}

### Обвязка для варьирования свойства + 10%

In [ ]:
pc_110_dict = {}

base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_pc110 = Composition(przlm_dict)
for component in composition_pc110.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        pc_110_dict[component] = composition_pc110.COMPOSITION_PROPERTIES[composition_pc110.COMPOSITION_PROPERTIES['key_0'] == component]['critical_pressure'].iloc[0]
    else:
        pc_110_dict[component] = composition_pc110.COMPOSITION_PROPERTIES[composition_pc110.COMPOSITION_PROPERTIES['key_0'] == component]['critical_pressure'].iloc[0] * 1.1
composition_pc110.set_property_dict('critical_pressure', pc_110_dict)

In [ ]:
composition_pc110.COMPOSITION_PROPERTIES

In [ ]:
model_pc110 = CompositionalModel(composition_pc110)
model_pc110.flash(conds)
model_pc110._flash_results

In [ ]:
pc110_sat_p = model_pc110.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_pc110 = PhaseDiagram(composition_pc110, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_pc110.calc_phase_diagram('PREOS')
phase_env_pc110_data = phase_env_pc110.get_phase_diagram_data()

In [ ]:
pc110_flash_results = model_pc110._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
pc110_flash_dict = {'Fv':pc110_flash_results.Fv,
                   'z_vap': pc110_flash_results.vapour_z,
                   'z_liquid':pc110_flash_results.liquid_z,
                   'density_liquid':pc110_flash_results.liquid_density,
                   'density_vapour':pc110_flash_results.vapour_density,
                   'Psat' : pc110_sat_p}

### Обвязка для варьирования свойства -10%

In [ ]:
pc_90_dict = {}

base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_pc90 = Composition(przlm_dict)
for component in composition_pc90.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        pc_90_dict[component] = composition_pc90.COMPOSITION_PROPERTIES[composition_pc90.COMPOSITION_PROPERTIES['key_0'] == component]['critical_pressure'].iloc[0]
    else:
        pc_90_dict[component] = composition_pc90.COMPOSITION_PROPERTIES[composition_pc90.COMPOSITION_PROPERTIES['key_0'] == component]['critical_pressure'].iloc[0] * 0.9
composition_pc90.set_property_dict('critical_pressure', pc_90_dict)

In [ ]:
composition_pc90.COMPOSITION_PROPERTIES

In [ ]:
model_pc90 = CompositionalModel(composition_pc90)
model_pc90.flash(conds)
model_pc90._flash_results

In [ ]:
pc90_sat_p = model_pc90.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_pc90 = PhaseDiagram(composition_pc90, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_pc90.calc_phase_diagram('PREOS')
phase_env_pc90_data = phase_env_pc90.get_phase_diagram_data()

In [ ]:
pc90_flash_results = model_pc90._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
pc90_flash_dict = {'Fv':pc90_flash_results.Fv,
                   'z_vap': pc90_flash_results.vapour_z,
                   'z_liquid':pc90_flash_results.liquid_z,
                   'density_liquid':pc90_flash_results.liquid_density,
                   'density_vapour':pc90_flash_results.vapour_density,
                   'Psat' : pc90_sat_p}

### Обвязка для варьирования свойства -20%

In [ ]:
pc_80_dict = {}

base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_pc80 = Composition(przlm_dict)
for component in composition_pc80.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        pc_80_dict[component] = composition_pc80.COMPOSITION_PROPERTIES[composition_pc80.COMPOSITION_PROPERTIES['key_0'] == component]['critical_pressure'].iloc[0]
    else:
        pc_80_dict[component] = composition_pc80.COMPOSITION_PROPERTIES[composition_pc80.COMPOSITION_PROPERTIES['key_0'] == component]['critical_pressure'].iloc[0] * 0.8
composition_pc80.set_property_dict('critical_pressure', pc_80_dict)

In [ ]:
model_pc80 = CompositionalModel(composition_pc80)
model_pc80.flash(conds)
pc80_flash_results = model_pc80._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
pc80_sat_p = model_pc80.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_pc80 = PhaseDiagram(composition_pc80, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_pc80.calc_phase_diagram('PREOS')
phase_env_pc80_data = phase_env_pc80.get_phase_diagram_data()

In [ ]:
pc80_flash_dict = {'Fv':pc80_flash_results.Fv,
                   'z_vap': pc80_flash_results.vapour_z,
                   'z_liquid':pc80_flash_results.liquid_z,
                   'density_liquid':pc80_flash_results.liquid_density,
                   'density_vapour':pc80_flash_results.vapour_density,
                   'Psat' : pc80_sat_p}

### Результаты Рс

#### Датафрейм

In [ ]:
import pandas as pd

In [ ]:
pc_df_base = pd.DataFrame.from_dict([base_flash_dict]).transpose()
pc120_df = pd.DataFrame.from_dict([pc120_flash_dict]).transpose()
pc110_df = pd.DataFrame.from_dict([pc110_flash_dict]).transpose()
pc90_df = pd.DataFrame.from_dict([pc90_flash_dict]).transpose()
pc80_df = pd.DataFrame.from_dict([pc80_flash_dict]).transpose()

sens_pc_df = pd.concat([pc80_df, pc90_df, pc_df_base, pc110_df, pc120_df], axis = 1)
sens_pc_df.columns = ['Pc * 0.8','Pc * 0.9', 'Pc', 'Pc * 1.1', 'Pc * 1.2']
sens_pc_df

#### Фазовые

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
sns.lineplot(marker='',data = phase_env_pc80_data, x= phase_env_pc80_data['Temp'], y= phase_env_pc80_data['Up'], color = 'orange', label = '80% Pc')
sns.lineplot(marker='',data = phase_env_pc80_data, x= phase_env_pc80_data['Temp'], y= phase_env_pc80_data['Low'], color = 'orange')
sns.lineplot(marker='x',data = phase_env_pc90_data, x= phase_env_pc90_data['Temp'], y= phase_env_pc90_data['Up'], color = 'green', label = '90% Pc')
sns.lineplot(marker='x',data = phase_env_pc90_data, x= phase_env_pc90_data['Temp'], y= phase_env_pc90_data['Low'], color = 'green')
sns.lineplot(marker='o',data = phase_env_base_data, x= phase_env_base_data['Temp'], y= phase_env_base_data['Up'], color = 'blue', label = 'base Pc')
sns.lineplot(marker='o',data = phase_env_base_data, x= phase_env_base_data['Temp'], y= phase_env_base_data['Low'], color = 'blue')
sns.lineplot(marker='x',data = phase_env_pc110_data, x= phase_env_pc110_data['Temp'], y= phase_env_pc110_data['Up'], color = 'red', label = '110% Pc')
sns.lineplot(marker='x',data = phase_env_pc110_data, x= phase_env_pc110_data['Temp'], y= phase_env_pc110_data['Low'], color = 'red')
sns.lineplot(marker='',data = phase_env_pc120_data, x= phase_env_pc120_data['Temp'], y= phase_env_pc120_data['Up'], color = 'gray', label = '120% Pc')
sns.lineplot(marker='',data = phase_env_pc120_data, x= phase_env_pc120_data['Temp'], y= phase_env_pc120_data['Low'], color = 'gray')
sns.scatterplot(x = [60], y = [12], color = 'black', marker = 'x')
# sns.scatterplot(marker = 'o', x = [60, 60, 60, 60, 60, 60, 60], y = [23, 21, 19, 17, 15, 13, 11], label = 'CCE')
# sns.scatterplot(marker = 'o', x = [60, 20, 20, 20], y = [25, 0.7, 0.3,0.1], label = 'Separator test')
plt.xlabel('Temperature, K')
plt.ylabel('Pressure, MPa')
plt.title('Phase envelope sensetivity to critical pressure')

In [ ]:
sns.lineplot(marker='o',data = phase_env_base_data, x= phase_env_base_data['Temp'], y= phase_env_base_data['Up'], color = 'blue', label = 'base Pc')
sns.lineplot(marker='o',data = phase_env_base_data, x= phase_env_base_data['Temp'], y= phase_env_base_data['Low'], color = 'blue')
sns.lineplot(marker='x',data = phase_env_pc110_data, x= phase_env_pc110_data['Temp'], y= phase_env_pc110_data['Up'], color = 'red', label = '110% Pc')
sns.lineplot(marker='x',data = phase_env_pc110_data, x= phase_env_pc110_data['Temp'], y= phase_env_pc110_data['Low'], color = 'red')
sns.lineplot(marker='',data = phase_env_pc90_data, x= phase_env_pc90_data['Temp'], y= phase_env_pc90_data['Up'], color = 'green', label = '90% Pc')
sns.lineplot(marker='',data = phase_env_pc90_data, x= phase_env_pc90_data['Temp'], y= phase_env_pc90_data['Low'], color = 'green')
plt.ylim((4,11))
plt.xlim(0, 100)

### Сепаратор тест

In [ ]:
model_pc80.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
model_pc90.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
base_model.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
model_pc110.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
model_pc120.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])

In [ ]:
dle_res_view = DLEResultsViewer()
dle_res_view.view(model_pc120.experiments.SEPARATORTEST_MOD.result)

In [ ]:
model_pc120.experiments.SEPARATORTEST_MOD.result.rs

In [ ]:
sns.lineplot(marker='', x= model_pc120.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc120.experiments.SEPARATORTEST_MOD.result.rs, color = 'gray', label = '120% Pc')
sns.lineplot(marker='', x= model_pc110.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc110.experiments.SEPARATORTEST_MOD.result.rs, color = 'red', label = '110% Pc')
sns.lineplot(marker='', x= base_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= base_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'blue', label = 'base Pc')
sns.lineplot(marker='', x= model_pc90.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc90.experiments.SEPARATORTEST_MOD.result.rs, color = 'green', label = '90% Pc')
sns.lineplot(marker='', x= model_pc80.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc80.experiments.SEPARATORTEST_MOD.result.rs, color = 'orange', label = '80% Pc')
sns.lineplot(marker='o', x = [0.1013, 0.81, 13.18, 25.28], y = [0, 2.8, 40.4, 40.4], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test GOR sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='', x= model_pc120.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc120.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'gray', label = '120% Pc')
sns.lineplot(marker='', x= model_pc110.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc110.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'red', label = '110% Pc')
sns.lineplot(marker='', x= base_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= base_model.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'blue', label = 'base Pc')
sns.lineplot(marker='', x= model_pc90.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc90.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'green', label = '90% Pc')
sns.lineplot(marker='', x= model_pc80.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc80.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'orange', label = '80% Pc')
sns.lineplot(marker='o', x = [0.1013, 0.81, 13.18, 25.28], y = [0.9298, 0.9223, 0.8775, 0.8859], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('Liquid density, g/sm3')
plt.title('Separator test liquid density sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='', x= model_pc120.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc120.experiments.SEPARATORTEST_MOD.result.bo, color = 'gray', label = '120% Pc')
sns.lineplot(marker='', x= model_pc110.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc110.experiments.SEPARATORTEST_MOD.result.bo, color = 'red', label = '110% Pc')
sns.lineplot(marker='', x= base_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= base_model.experiments.SEPARATORTEST_MOD.result.bo, color = 'blue', label = 'base Pc')
sns.lineplot(marker='', x= model_pc90.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc90.experiments.SEPARATORTEST_MOD.result.bo, color = 'green', label = '90% Pc')
sns.lineplot(marker='', x= model_pc80.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_pc80.experiments.SEPARATORTEST_MOD.result.bo, color = 'orange', label = '80% Pc')
sns.lineplot(marker='o', x = [0.1013, 0.81, 13.18, 25.28], y = [1, 1.011, 1.1, 1.089], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('Formation volume factor, sm3/sm3')
plt.title('Separator test FVF sensetivity to critial pressure')

### CCE

In [ ]:
cce_pres_arr = [
27.68,
25.28,
23.54,
22.16,
20.79,
19.41,
18.03,
17.34,
16.65,
15.96,
15.57,
15.4,
14.93,
14.58,
13.89,
13.18
]

cce_v_vsat = [
0.989,
0.99,
0.992,
0.993,
0.994,
0.995,
0.996,
0.997,
0.997,
0.998,
0.998,
0.998,
0.999,
0.999,
0.999,
1,

]

cce_lden = [
0.8875,
0.8859,
0.8848,
0.8838,
0.8829,
0.8819,
0.881,
0.8805,
0.88,
0.8795,
0.8792,
0.8791,
0.8787,
0.8785,
0.878,
0.8775
]

In [ ]:
model_pc80.experiments.CCE.calculate(p_resirvoir=25.28,temperature=65.6, pressure_by_stages=cce_pres_arr)
model_pc90.experiments.CCE.calculate(p_resirvoir=25.28,temperature=65.6, pressure_by_stages=cce_pres_arr)
base_model.experiments.CCE.calculate(p_resirvoir=25.28,temperature=65.6, pressure_by_stages=cce_pres_arr)
model_pc110.experiments.CCE.calculate(p_resirvoir=25.28,temperature=65.6, pressure_by_stages=cce_pres_arr)
model_pc120.experiments.CCE.calculate(p_resirvoir=25.28,temperature=65.6, pressure_by_stages=cce_pres_arr)

In [ ]:
len(cce_lden) == len(cce_pres_arr)

In [ ]:
sns.lineplot(marker='', x= model_pc120.experiments.CCE.result.pressure, y= model_pc120.experiments.CCE.result.liquid_density, color = 'gray', label = '120% Pc')
sns.lineplot(marker='x', x= model_pc110.experiments.CCE.result.pressure, y= model_pc110.experiments.CCE.result.liquid_density, color = 'red', label = '110% Pc')
sns.lineplot(marker='', x= base_model.experiments.CCE.result.pressure, y= base_model.experiments.CCE.result.liquid_density, color = 'blue', label = 'base Pc')
sns.lineplot(marker='x', x= model_pc90.experiments.CCE.result.pressure, y= model_pc90.experiments.CCE.result.liquid_density, color = 'green', label = '90% Pc')
sns.lineplot(marker='', x= model_pc80.experiments.CCE.result.pressure, y= model_pc80.experiments.CCE.result.liquid_density, color = 'orange', label = '80% Pc')
sns.lineplot(marker = 'o', x = cce_pres_arr, y = cce_lden)
plt.xlabel('Pressure, MPa')
plt.ylabel('Liquid density, g/sm3')
plt.title('CCE liquid density sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='', x= model_pc120.experiments.CCE.result.pressure, y= model_pc120.experiments.CCE.dataframe['V/Vsat'], color = 'gray', label = '120% Pc')
sns.lineplot(marker='x', x= model_pc110.experiments.CCE.result.pressure, y= model_pc110.experiments.CCE.dataframe['V/Vsat'], color = 'red', label = '110% Pc')
sns.lineplot(marker='', x= base_model.experiments.CCE.result.pressure, y= base_model.experiments.CCE.dataframe['V/Vsat'], color = 'blue', label = 'base Pc')
sns.lineplot(marker='x', x= model_pc90.experiments.CCE.result.pressure, y= model_pc90.experiments.CCE.dataframe['V/Vsat'], color = 'green', label = '90% Pc')
sns.lineplot(marker='', x= model_pc80.experiments.CCE.result.pressure, y= model_pc80.experiments.CCE.dataframe['V/Vsat'], color = 'orange', label = '80% Pc')
sns.lineplot(marker = 'o', x = cce_pres_arr, y = cce_v_vsat)
plt.xlabel('Pressure, MPa')
plt.ylabel('V/Vsat, sm3/sm3')
plt.title('CCE V/Vsat sensetivity to critial pressure')

## Чувствительность к Tc

### Обвязка для варьирования параметра -15%

In [ ]:
tc_80_dict = {}

base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_tc80 = Composition(przlm_dict)
for component in composition_tc80.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        tc_80_dict[component] = composition_tc80.COMPOSITION_PROPERTIES[composition_tc80.COMPOSITION_PROPERTIES['key_0'] == component]['critical_temperature'].iloc[0]
    else:
        tc_80_dict[component] = composition_tc80.COMPOSITION_PROPERTIES[composition_tc80.COMPOSITION_PROPERTIES['key_0'] == component]['critical_temperature'].iloc[0] * 0.85
composition_tc80.set_property_dict('critical_temperature', tc_80_dict)

In [ ]:
model_tc80 = CompositionalModel(composition_tc80)
model_tc80.flash(conds)
tc80_flash_results = model_tc80._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
tc80_sat_p = model_tc80.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_tc80 = PhaseDiagram(composition_tc80, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_tc80.calc_phase_diagram('PREOS')
phase_env_tc80_data = phase_env_tc80.get_phase_diagram_data()

In [ ]:
tc80_flash_dict = {'Fv':tc80_flash_results.Fv,
                   'z_vap': tc80_flash_results.vapour_z,
                   'z_liquid':tc80_flash_results.liquid_z,
                   'density_liquid':tc80_flash_results.liquid_density,
                   'density_vapour':tc80_flash_results.vapour_density,
                   'Psat' : tc80_sat_p}

### Обвязка для варьирования параметра -10%

In [ ]:
tc_90_dict = {}

base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_tc90 = Composition(przlm_dict)
for component in composition_tc90.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        tc_90_dict[component] = composition_tc90.COMPOSITION_PROPERTIES[composition_tc90.COMPOSITION_PROPERTIES['key_0'] == component]['critical_temperature'].iloc[0]
    else:
        tc_90_dict[component] = composition_tc90.COMPOSITION_PROPERTIES[composition_tc90.COMPOSITION_PROPERTIES['key_0'] == component]['critical_temperature'].iloc[0] * 0.9
composition_tc90.set_property_dict('critical_temperature', tc_90_dict)

In [ ]:
model_tc90 = CompositionalModel(composition_tc90)
model_tc90.flash(conds)
tc90_flash_results = model_tc90._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
tc90_sat_p = model_tc90.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_tc90 = PhaseDiagram(composition_tc90, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_tc90.calc_phase_diagram('PREOS')
phase_env_tc90_data = phase_env_tc90.get_phase_diagram_data()

In [ ]:
tc90_flash_dict = {'Fv':tc90_flash_results.Fv,
                   'z_vap': tc90_flash_results.vapour_z,
                   'z_liquid':tc90_flash_results.liquid_z,
                   'density_liquid':tc90_flash_results.liquid_density,
                   'density_vapour':tc90_flash_results.vapour_density,
                   'Psat' : tc90_sat_p}

### Обвязка для варьирования параметра + 10%

In [ ]:
tc_110_dict = {}

base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_tc110 = Composition(przlm_dict)
for component in composition_tc110.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        tc_110_dict[component] = composition_tc110.COMPOSITION_PROPERTIES[composition_tc110.COMPOSITION_PROPERTIES['key_0'] == component]['critical_temperature'].iloc[0]
    else:
        tc_110_dict[component] = composition_tc110.COMPOSITION_PROPERTIES[composition_tc110.COMPOSITION_PROPERTIES['key_0'] == component]['critical_temperature'].iloc[0] * 1.1
composition_tc110.set_property_dict('critical_temperature', tc_110_dict)

In [ ]:
model_tc110 = CompositionalModel(composition_tc110)
model_tc110.flash(conds)
tc110_flash_results = model_tc110._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
tc110_sat_p = model_tc110.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_tc110 = PhaseDiagram(composition_tc110, p_max=20, t_min=0, t_max=650, t_step=10)
phase_env_tc110.calc_phase_diagram('PREOS')
phase_env_tc110_data = phase_env_tc110.get_phase_diagram_data()

In [ ]:
tc110_flash_dict = {'Fv':tc110_flash_results.Fv,
                   'z_vap': tc110_flash_results.vapour_z,
                   'z_liquid':tc110_flash_results.liquid_z,
                   'density_liquid':tc110_flash_results.liquid_density,
                   'density_vapour':tc110_flash_results.vapour_density,
                   'Psat' : tc110_sat_p}

### Обвязка для варьирования параметров +20%

In [ ]:
tc_120_dict = {}

base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_tc120 = Composition(przlm_dict)
for component in composition_tc120.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        tc_120_dict[component] = composition_tc120.COMPOSITION_PROPERTIES[composition_tc120.COMPOSITION_PROPERTIES['key_0'] == component]['critical_temperature'].iloc[0]
    else:
        tc_120_dict[component] = composition_tc120.COMPOSITION_PROPERTIES[composition_tc120.COMPOSITION_PROPERTIES['key_0'] == component]['critical_temperature'].iloc[0] * 1.2
composition_tc120.set_property_dict('critical_temperature', tc_120_dict)

In [ ]:
model_tc120 = CompositionalModel(composition_tc120)
model_tc120.flash(conds)
tc120_flash_results = model_tc120._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
tc120_sat_p = model_tc120.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_tc120 = PhaseDiagram(composition_tc120, p_max=20, t_min=0, t_max=780, t_step=10)
phase_env_tc120.calc_phase_diagram('PREOS')
phase_env_tc120_data = phase_env_tc120.get_phase_diagram_data()

In [ ]:
tc120_flash_dict = {'Fv':tc120_flash_results.Fv,
                   'z_vap': tc120_flash_results.vapour_z,
                   'z_liquid':tc120_flash_results.liquid_z,
                   'density_liquid':tc120_flash_results.liquid_density,
                   'density_vapour':tc120_flash_results.vapour_density,
                   'Psat' : tc120_sat_p}

### Результаты Тс

In [ ]:
tc_df_base = pd.DataFrame.from_dict([base_flash_dict]).transpose()
tc80_df = pd.DataFrame.from_dict([tc80_flash_dict]).transpose()
tc90_df = pd.DataFrame.from_dict([tc90_flash_dict]).transpose()
sens_pc_df = pd.concat([tc80_df, tc90_df, tc_df_base], axis = 1)
sens_pc_df.columns = ['Tc * 0.8', 'Tc * 0.9', 'Tc']
sens_pc_df

In [ ]:
sns.lineplot(marker='',data = phase_env_tc80_data, x= phase_env_tc80_data['Temp'], y= phase_env_tc80_data['Up'], color = 'yellow', label = '80% Tc')
sns.lineplot(marker='',data = phase_env_tc80_data, x= phase_env_tc80_data['Temp'], y= phase_env_tc80_data['Low'], color = 'yellow')

sns.lineplot(marker='x',data = phase_env_tc90_data, x= phase_env_tc90_data['Temp'], y= phase_env_tc90_data['Up'], color = 'green', label = '90% Tc')
sns.lineplot(marker='x',data = phase_env_tc90_data, x= phase_env_tc90_data['Temp'], y= phase_env_tc90_data['Low'], color = 'green')

sns.lineplot(marker='o',data = phase_env_base_data, x= phase_env_base_data['Temp'], y= phase_env_base_data['Up'], color = 'blue', label = 'base Tc')
sns.lineplot(marker='o',data = phase_env_base_data, x= phase_env_base_data['Temp'], y= phase_env_base_data['Low'], color = 'blue')

sns.lineplot(marker='x',data = phase_env_tc110_data, x= phase_env_tc110_data['Temp'], y= phase_env_tc110_data['Up'], color = 'red', label = '110% Tc')
sns.lineplot(marker='x',data = phase_env_tc110_data, x= phase_env_tc110_data['Temp'], y= phase_env_tc110_data['Low'], color = 'red')

sns.lineplot(marker='',data = phase_env_tc120_data, x= phase_env_tc120_data['Temp'], y= phase_env_tc120_data['Up'], color = 'gray', label = '120% Tc')
sns.lineplot(marker='',data = phase_env_tc120_data, x= phase_env_tc120_data['Temp'], y= phase_env_tc120_data['Low'], color = 'gray')

### Сепаратор тест

In [ ]:
model_tc80.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
model_tc90.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
base_model.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
model_tc110.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])
model_tc120.experiments.SEPARATORTEST_MOD.calculate(25.8, 65.6, [ 0.81], [ 49.3])

In [ ]:
sns.lineplot(marker='', x= model_tc120.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_tc120.experiments.SEPARATORTEST_MOD.result.rs, color = 'gray', label = '120% Tc')
sns.lineplot(marker='', x= model_tc110.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_tc110.experiments.SEPARATORTEST_MOD.result.rs, color = 'red', label = '110% Tc')
sns.lineplot(marker='', x= base_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= base_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'blue', label = 'base Tc')
sns.lineplot(marker='', x= model_tc90.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_tc90.experiments.SEPARATORTEST_MOD.result.rs, color = 'green', label = '90% Tc')
sns.lineplot(marker='', x= model_tc80.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_tc80.experiments.SEPARATORTEST_MOD.result.rs, color = 'orange', label = '80% Tc')
sns.lineplot(marker='o', x = [0.1013, 0.81, 13.18, 25.28], y = [0, 2.8, 40.4, 40.4], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test GOR sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='', x= model_tc120.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_tc120.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'gray', label = '120% Tc')
sns.lineplot(marker='', x= model_tc110.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_tc110.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'red', label = '110% Tc')
sns.lineplot(marker='', x= base_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= base_model.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'blue', label = 'base Tc')
sns.lineplot(marker='', x= model_tc90.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_tc90.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'green', label = '90% Tc')
sns.lineplot(marker='', x= model_tc80.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_tc80.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'orange', label = '80% Tc')
sns.lineplot(marker='o', x = [0.1013, 0.81, 13.18, 25.28], y = [0.9298, 0.9223, 0.8775, 0.8859], label ='LAB')
plt.xlabel('Pressure, MPa')
plt.ylabel('Liquid density, g/sm3')
plt.title('Separator test liquid density sensetivity to critial pressure')

## Ацентрический фактор

### Обвязка для варьирования параметра 90%

In [ ]:
ac_90_dict = {}

base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_ac90 = Composition(przlm_dict)
for component in composition_ac90.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        ac_90_dict[component] = composition_ac90.COMPOSITION_PROPERTIES[composition_ac90.COMPOSITION_PROPERTIES['key_0'] == component]['acentric_factor'].iloc[0]
    else:
        ac_90_dict[component] = composition_ac90.COMPOSITION_PROPERTIES[composition_ac90.COMPOSITION_PROPERTIES['key_0'] == component]['acentric_factor'].iloc[0] * 0.9
composition_ac90.set_property_dict('acentric_factor', ac_90_dict)

In [ ]:
model_ac90 = CompositionalModel(composition_ac90)
model_ac90.flash(conds)
ac90_flash_results = model_ac90._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
ac90_sat_p = model_ac90.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_ac90 = PhaseDiagram(composition_ac90, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_ac90.calc_phase_diagram('PREOS')
phase_env_ac90_data = phase_env_ac90.get_phase_diagram_data()

In [ ]:
tc90_flash_dict = {'Fv':ac90_flash_results.Fv,
                   'z_vap': ac90_flash_results.vapour_z,
                   'z_liquid':ac90_flash_results.liquid_z,
                   'density_liquid':ac90_flash_results.liquid_density,
                   'density_vapour':ac90_flash_results.vapour_density,
                   'Psat' : ac90_sat_p}

### Обвязка для варьирования параметра 80%

In [ ]:
ac_80_dict = {}

base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_ac80 = Composition(przlm_dict)
for component in composition_ac80.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        ac_80_dict[component] = composition_ac80.COMPOSITION_PROPERTIES[composition_ac80.COMPOSITION_PROPERTIES['key_0'] == component]['acentric_factor'].iloc[0]
    else:
        ac_80_dict[component] = composition_ac80.COMPOSITION_PROPERTIES[composition_ac80.COMPOSITION_PROPERTIES['key_0'] == component]['acentric_factor'].iloc[0] * 0.8
composition_ac80.set_property_dict('acentric_factor', ac_80_dict)

In [ ]:
model_ac80 = CompositionalModel(composition_ac80)
model_ac80.flash(conds)
ac80_flash_results = model_ac80._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
ac80_sat_p = model_ac80.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_ac80 = PhaseDiagram(composition_ac80, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_ac80.calc_phase_diagram('PREOS')
phase_env_ac80_data = phase_env_ac80.get_phase_diagram_data()

In [ ]:
tc80_flash_dict = {'Fv':ac80_flash_results.Fv,
                   'z_vap': ac80_flash_results.vapour_z,
                   'z_liquid':ac80_flash_results.liquid_z,
                   'density_liquid':ac80_flash_results.liquid_density,
                   'density_vapour':ac80_flash_results.vapour_density,
                   'Psat' : ac80_sat_p}

### Обвязка для варьирования параметра 110%

In [ ]:
ac_110_dict = {}

base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_ac110 = Composition(przlm_dict)
for component in composition_ac110.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        ac_110_dict[component] = composition_ac110.COMPOSITION_PROPERTIES[composition_ac110.COMPOSITION_PROPERTIES['key_0'] == component]['acentric_factor'].iloc[0]
    else:
        ac_110_dict[component] = composition_ac110.COMPOSITION_PROPERTIES[composition_ac110.COMPOSITION_PROPERTIES['key_0'] == component]['acentric_factor'].iloc[0] * 1.1
composition_ac110.set_property_dict('acentric_factor', ac_110_dict)

In [ ]:
model_ac110 = CompositionalModel(composition_ac110)
model_ac110.flash(conds)
ac110_flash_results = model_ac110._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
ac110_sat_p = model_ac110.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_ac110 = PhaseDiagram(composition_ac110, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_ac110.calc_phase_diagram('PREOS')
phase_env_ac110_data = phase_env_ac110.get_phase_diagram_data()

In [ ]:
tc80_flash_dict = {'Fv':ac110_flash_results.Fv,
                   'z_vap': ac110_flash_results.vapour_z,
                   'z_liquid':ac110_flash_results.liquid_z,
                   'density_liquid':ac110_flash_results.liquid_density,
                   'density_vapour':ac110_flash_results.vapour_density,
                   'Psat' : ac110_sat_p}

### Обвязка параметров 120%

In [ ]:
ac_120_dict = {}

base_components = ['C1', 'C2', 'C3', 'iC4', 'nC4', 'iC5', 'nC5', 'CO2', 'H2S', 'N2']
composition_ac120 = Composition(przlm_dict)
for component in composition_ac120.COMPOSITION_PROPERTIES['key_0']:
    if component in base_components:
        ac_120_dict[component] = composition_ac120.COMPOSITION_PROPERTIES[composition_ac120.COMPOSITION_PROPERTIES['key_0'] == component]['acentric_factor'].iloc[0]
    else:
        ac_120_dict[component] = composition_ac120.COMPOSITION_PROPERTIES[composition_ac120.COMPOSITION_PROPERTIES['key_0'] == component]['acentric_factor'].iloc[0] * 1.2
composition_ac120.set_property_dict('acentric_factor', ac_120_dict)

In [ ]:
model_ac120 = CompositionalModel(composition_ac120)
model_ac120.flash(conds)
ac120_flash_results = model_ac120._flash_results[f'TwoPhaseFlash_{conds.p}_{conds.t - 273.14}']

In [ ]:
ac120_sat_p = model_ac120.saturation_pressure(conds.t - 273.14, p_max=20)

In [ ]:
phase_env_ac120 = PhaseDiagram(composition_ac120, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_ac120.calc_phase_diagram('PREOS')
phase_env_ac120_data = phase_env_ac120.get_phase_diagram_data()

In [ ]:
tc80_flash_dict = {'Fv':ac110_flash_results.Fv,
                   'z_vap': ac110_flash_results.vapour_z,
                   'z_liquid':ac110_flash_results.liquid_z,
                   'density_liquid':ac110_flash_results.liquid_density,
                   'density_vapour':ac110_flash_results.vapour_density,
                   'Psat' : ac110_sat_p}

### Результаты Ас

In [ ]:
sns.lineplot(marker='',data = phase_env_ac80_data, x= phase_env_ac80_data['Temp'], y= phase_env_ac80_data['Up'], color = 'orange', label = '80% Ac')
sns.lineplot(marker='',data = phase_env_ac80_data, x= phase_env_ac80_data['Temp'], y= phase_env_ac80_data['Low'], color = 'orange')

sns.lineplot(marker='x',data = phase_env_ac90_data, x= phase_env_ac90_data['Temp'], y= phase_env_ac90_data['Up'], color = 'green', label = '90% Ac')
sns.lineplot(marker='x',data = phase_env_ac90_data, x= phase_env_ac90_data['Temp'], y= phase_env_ac90_data['Low'], color = 'green')

sns.lineplot(marker='o',data = phase_env_base_data, x= phase_env_base_data['Temp'], y= phase_env_base_data['Up'], color = 'blue', label = 'base Ac')
sns.lineplot(marker='o',data = phase_env_base_data, x= phase_env_base_data['Temp'], y= phase_env_base_data['Low'], color = 'blue')

sns.lineplot(marker='x',data = phase_env_ac110_data, x= phase_env_ac110_data['Temp'], y= phase_env_ac110_data['Up'], color = 'red', label = '110% Ac')
sns.lineplot(marker='x',data = phase_env_ac110_data, x= phase_env_ac110_data['Temp'], y= phase_env_ac110_data['Low'], color = 'red')

sns.lineplot(marker='',data = phase_env_ac120_data, x= phase_env_ac120_data['Temp'], y= phase_env_ac120_data['Up'], color = 'gray', label = '120% Ac')
sns.lineplot(marker='',data = phase_env_ac120_data, x= phase_env_ac120_data['Temp'], y= phase_env_ac120_data['Low'], color = 'gray')

sns.scatterplot(x = [60], y = [12], color = 'black', marker = 'x', label = 'Psat')
plt.xlabel('Temperature, K')
plt.ylabel('Pressure, MPa')
plt.title('Phase envelope sensetivity to acentric factor')

### Сепаратор тест

In [ ]:
model_ac80.experiments.SEPARATORTEST_MOD.calculate(25, 60, [0.7, 0.3], [20, 20])
model_ac90.experiments.SEPARATORTEST_MOD.calculate(25, 60, [0.7, 0.3], [20, 20])
base_model.experiments.SEPARATORTEST_MOD.calculate(25, 60, [0.7, 0.3], [20, 20])
model_ac110.experiments.SEPARATORTEST_MOD.calculate(25, 60, [0.7, 0.3], [20, 20])
model_ac120.experiments.SEPARATORTEST_MOD.calculate(25, 60, [0.7, 0.3], [20, 20])

In [ ]:
sns.lineplot(marker='', x= model_ac120.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ac120.experiments.SEPARATORTEST_MOD.result.rs, color = 'gray', label = '120% Tc')
sns.lineplot(marker='', x= model_ac110.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ac110.experiments.SEPARATORTEST_MOD.result.rs, color = 'red', label = '110% Tc')
sns.lineplot(marker='', x= base_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= base_model.experiments.SEPARATORTEST_MOD.result.rs, color = 'blue', label = 'base Tc')
sns.lineplot(marker='', x= model_ac90.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ac90.experiments.SEPARATORTEST_MOD.result.rs, color = 'green', label = '90% Tc')
sns.lineplot(marker='', x= model_ac80.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ac80.experiments.SEPARATORTEST_MOD.result.rs, color = 'orange', label = '80% Tc')

plt.xlabel('Pressure, MPa')
plt.ylabel('GOR, sm3/sm3')
plt.title('Separator test GOR sensetivity to critial pressure')

In [ ]:
sns.lineplot(marker='', x= model_ac120.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ac120.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'gray', label = '120% Pc')
sns.lineplot(marker='', x= model_ac110.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ac110.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'red', label = '110% Pc')
sns.lineplot(marker='', x= base_model.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= base_model.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'blue', label = 'base Pc')
sns.lineplot(marker='', x= model_ac90.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ac90.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'green', label = '90% Pc')
sns.lineplot(marker='', x= model_ac80.experiments.SEPARATORTEST_MOD.result.pressure_arr, y= model_ac80.experiments.SEPARATORTEST_MOD.result.liquid_density_arr, color = 'orange', label = '80% Pc')

plt.xlabel('Pressure, MPa')
plt.ylabel('Liquid density, g/sm3')
plt.title('Separator test liquid density sensetivity to critial pressure')