In [1]:
from calculations.Composition.Composition import Composition
from calculations.Utils.Conditions import Conditions
from calculations.CompositionalModel.CompositionalModel import CompositionalModel
from calculations.EOS.PenelouxVolumeCorrection import PenelouxVolumeCorrection
from calculations.Utils.ResultsViewer import FlashResultsViewer, DLEResultsViewer, SeparatorTestResultsViewer, StandardSeparationResultsViewer
from calculations.Utils.CompositionLoader import CompositionExcelLoader
from calculations.PhaseDiagram.PhaseDiagram_v4 import PhaseDiagram

# KRSNLN

In [2]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\krsnln.xlsx')
krsnln_dict = excel_loader.load(header=True, sheet='to_model')

In [3]:
krsnln_rizari_daubert_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'rizari_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_rizari_daubert_composition.edit_component_properties('C36', {'molar_mass' : 569.684})

krsnln_pedersen_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_pedersen_composition.edit_component_properties('C36', {'molar_mass' : 569.684})

krsnln_pedersen_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_pedersen_composition.edit_component_properties('C36', {'molar_mass' : 569.684})

krsnln_kesler_lee_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'kesler_lee',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_kesler_lee_composition.edit_component_properties('C36', {'molar_mass' : 569.684})

krsnln_sim_daubert_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'sim_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_sim_daubert_composition.edit_component_properties('C36', {'molar_mass' : 569.684})

krsnln_standing_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'standing',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_standing_composition.edit_component_properties('C36', {'molar_mass' : 569.684})

krsnln_twu_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'twu',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_twu_composition.edit_component_properties('C36', {'molar_mass' : 569.684})

krsnln_brs_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pc_from_eos',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_brs_composition.edit_component_properties('C36', {'molar_mass' : 569.684})

krsnln_cavett_composition = Composition(zi = krsnln_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'cavett',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
krsnln_cavett_composition.edit_component_properties('C36', {'molar_mass' : 569.684})

[48221.24373018825, 7.847137451171875e-07, 2.612502592380524]
[51841.580192918664, 7.37030029296875e-07, 2.504066903224945]
[55469.74577746297, 6.526641845703125e-07, 2.359937429149628]
[58476.7740230504, 6.103439331054688e-07, 2.238572946369171]
[61180.57421952356, 5.806503295898437e-07, 2.127377448284149]
[64265.25884637073, 5.690078735351562e-07, 2.023625741592407]
[67375.41901898915, 4.950904846191407e-07, 1.9353407914466858]
[70741.48436851658, 4.738044738769531e-07, 1.8522458263397217]
[74237.17957228796, 4.053192138671875e-07, 1.7718574523086548]
[77425.00555926822, 3.570976257324219e-07, 1.6952133593444825]
[80770.17534483131, 3.2612228393554687e-07, 1.6354587503166198]
[83606.91905188299, 4.185523986816406e-07, 1.5803893739204407]
[86237.59135475723, 2.5655364990234373e-07, 1.5390845645561217]
[88946.66214269903, 3.0732345581054686e-07, 1.5012030418281554]
[92386.24693859594, 2.2333908081054688e-07, 1.4520334607810974]
[95612.39663189318, 2.3752975463867189e-07, 1.414208114048004]
[98766.39106791167, 2.994651794433594e-07, 1.3826028570365905]
[101822.43273751893, 2.5035476684570315e-07, 1.351588983024597]
[104953.42492336742, 2.131805419921875e-07, 1.318394122001648]
[108370.8285057871, 1.9366455078125e-07, 1.2893512241516114]
[112081.69957937855, 3.106460571289063e-07, 1.2600797185668946]
[115490.62820865371, 2.10540771484375e-07, 1.2335378388290406]
[118988.98284698727, 3.235092163085938e-07, 1.2087592810974122]
[122577.60676063679, 4.4605255126953127e-07, 1.1855770405426025]
[126481.75278829594, 4.215545654296875e-07, 1.1653494355316163]
[130258.84453701712, 2.1016693115234374e-07, 1.1449051802368164]
[134129.16381561558, -2.5726318359375e-08, 1.1256696437072753]
[137853.54929095745, 4.5510101318359377e-07, 1.1061294392623902]
[141908.00191587867, 1.577301025390625e-07, 1.0890463473892211]
[145807.7745739985, 1.560211181640625e-08, 1.0715414304275512]
[163756.70207335966, -3.64410400390625e-07, 0.9843962569274902]

In [4]:
krsnln_pedersen_composition.COMPOSITION_PROPERTIES

,key_0,0,molar_mass,gamma,Tb,critical_pressure,critical_temperature,acentric_factor,shift_parameter,critical_volume,bip,c5_plus_flag
0,N2,0.002610,28.013,0.4700,77.39,3.394000,126.190000,0.040000,-0.192700,0.090100,"{'CO2': 0, 'N2': 0, 'C1': 0.003, 'C2': 0.011, ...",0
1,CO2,0.014831,44.010,0.5000,194.67,7.387000,304.690000,0.225000,-0.081700,1.505735,"{'CO2': 0, 'N2': 0, 'C1': 0.004, 'C2': 0.009, ...",0
2,C1,0.389419,16.043,0.3300,111.67,4.604000,190.600000,0.013000,-0.159500,1.585828,"{'CO2': 0.004, 'N2': 0.003, 'C1': 0, 'C2': 0.0...",0
3,C2,0.103390,30.070,0.4500,184.56,4.884000,305.420000,0.099000,-0.113400,2.370730,"{'CO2': 0.009, 'N2': 0.011, 'C1': 0.024, 'C2':...",0
4,C3,0.078718,44.097,0.5077,231.11,4.246000,369.790000,0.152000,-0.086300,3.251740,"{'CO2': 0, 'N2': 0, 'C1': 0.004, 'C2': 0.009, ...",0
5,iC4,0.009781,58.124,0.5613,261.44,3.648000,408.090000,0.185000,-0.084400,4.212855,"{'CO2': 0.008, 'N2': 0.01, 'C1': 0.023, 'C2': ...",0
6,nC4,0.030433,58.124,0.5844,272.67,3.797000,425.190000,0.201000,-0.094000,4.084708,"{'CO2': 0.023, 'N2': 0.026, 'C1': 0.045, 'C2':...",0
7,iC5,0.008741,72.151,0.6274,301.00,3.389000,460.390000,0.227000,-0.060800,4.901640,"{'CO2': 0.04, 'N2': 0.044, 'C1': 0.067, 'C2': ...",0
8,nC5,0.017292,72.151,0.6301,309.22,3.370000,469.590000,0.251000,-0.039000,4.869612,"{'CO2': 0, 'N2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",0
9,C6,0.022392,86.178,0.6900,337.05,3.104000,507.500000,0.252000,-0.008000,5.926800,"{'CO2': 0.05, 'N2': 0.054, 'C1': 0.042, 'C2': ...",1
10,C7,0.032003,96.000,0.7270,365.05,3.068030,533.539281,0.306969,-0.039968,6.129490,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
11,C8,0.040134,107.000,0.7490,389.85,2.821376,553.255602,0.346274,-0.014077,6.781567,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
12,C9,0.029443,121.000,0.7680,415.35,2.547909,575.052576,0.394487,0.014491,7.657889,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
13,C10,0.025343,134.000,0.7820,438.95,2.347705,593.274803,0.437718,0.037589,8.488891,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
14,C11,0.020472,147.000,0.7930,460.35,2.183483,609.927686,0.479684,0.058077,9.338598,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
15,C12,0.017352,161.000,0.8040,481.45,2.045872,626.747369,0.523653,0.077782,10.255789,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
16,C13,0.016792,175.000,0.8150,500.35,1.941361,642.736213,0.566510,0.095481,11.166838,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
17,C14,0.014761,190.000,0.8260,519.55,1.852643,658.975483,0.611341,0.112604,12.144593,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
18,C15,0.012151,206.000,0.8360,539.15,1.773415,675.287628,0.658067,0.129122,13.201298,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
19,C16,0.010651,222.000,0.8430,556.15,1.699855,690.479097,0.703789,0.144131,14.292288,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
20,C17,0.009041,237.000,0.8510,573.15,1.650444,704.466862,0.745837,0.157037,15.293310,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
21,C18,0.008571,251.000,0.8560,586.15,1.603504,716.749565,0.784437,0.168206,16.260985,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
22,C19,0.008001,263.000,0.8610,598.15,1.572159,727.142166,0.817067,0.177185,17.079066,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
23,C20,0.006881,275.000,0.8660,611.15,1.545416,737.325647,0.849306,0.185673,17.895843,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
24,C21,0.005691,291.000,0.8710,624.15,1.509476,750.339037,0.891728,0.196305,19.011332,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
25,C22,0.005131,305.000,0.8760,636.15,1.485295,761.580729,0.928356,0.205034,19.975967,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
26,C23,0.004860,318.000,0.8810,648.15,1.467580,771.891492,0.961986,0.212708,20.863771,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
27,C24,0.004450,331.000,0.8850,659.15,1.449056,781.875437,0.995273,0.220005,21.769212,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
28,C25,0.003910,345.000,0.8880,670.15,1.427258,792.246255,1.030758,0.227478,22.770170,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
29,C26,0.003630,359.000,0.8920,681.15,1.411653,802.620422,1.065890,0.234587,23.751121,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
30,C27,0.003480,374.000,0.8960,692.15,1.396420,813.526294,1.103163,0.241834,24.807668,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
31,C28,0.002750,388.000,0.8990,702.15,1.381715,823.445652,1.137628,0.248281,25.810010,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
32,C29,0.002890,402.000,0.9020,711.15,1.368798,833.240286,1.171797,0.254448,26.812887,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
33,C30,0.002660,416.000,0.9050,719.15,1.357467,842.919147,1.205686,0.260356,27.816129,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
34,C31,0.002410,430.000,0.9090,728.15,1.350924,852.653378,1.239309,0.266024,28.794417,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
35,C32,0.002110,444.000,0.9120,736.15,1.342249,862.123957,1.272680,0.271469,29.797136,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
36,C33,0.001830,458.000,0.9150,744.15,1.334716,871.500520,1.305810,0.276706,30.799784,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
37,C34,0.001700,472.000,0.9170,751.15,1.324894,880.625853,1.338710,0.281750,31.829751,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
38,C35,0.001760,486.000,0.9200,759.15,1.319341,889.831562,1.371391,0.286612,32.832661,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
39,C36,0.021532,569.684,0.9220,766.15,1.250725,940.778229,1.562655,0.312472,39.346413,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1

In [6]:
krsnln_standing_composition.COMPOSITION_PROPERTIES

,key_0,0,molar_mass,gamma,Tb,critical_pressure,critical_temperature,acentric_factor,shift_parameter,critical_volume,bip,c5_plus_flag
0,N2,0.002610,28.013,0.4700,77.39,3.394000,126.190000,0.040000,-0.192700,0.090100,"{'CO2': 0, 'N2': 0, 'C1': 0.003, 'C2': 0.011, ...",0
1,CO2,0.014831,44.010,0.5000,194.67,7.387000,304.690000,0.225000,-0.081700,1.505735,"{'CO2': 0, 'N2': 0, 'C1': 0.004, 'C2': 0.009, ...",0
2,C1,0.389419,16.043,0.3300,111.67,4.604000,190.600000,0.013000,-0.159500,1.585828,"{'CO2': 0.004, 'N2': 0.003, 'C1': 0, 'C2': 0.0...",0
3,C2,0.103390,30.070,0.4500,184.56,4.884000,305.420000,0.099000,-0.113400,2.370730,"{'CO2': 0.009, 'N2': 0.011, 'C1': 0.024, 'C2':...",0
4,C3,0.078718,44.097,0.5077,231.11,4.246000,369.790000,0.152000,-0.086300,3.251740,"{'CO2': 0, 'N2': 0, 'C1': 0.004, 'C2': 0.009, ...",0
5,iC4,0.009781,58.124,0.5613,261.44,3.648000,408.090000,0.185000,-0.084400,4.212855,"{'CO2': 0.008, 'N2': 0.01, 'C1': 0.023, 'C2': ...",0
6,nC4,0.030433,58.124,0.5844,272.67,3.797000,425.190000,0.201000,-0.094000,4.084708,"{'CO2': 0.023, 'N2': 0.026, 'C1': 0.045, 'C2':...",0
7,iC5,0.008741,72.151,0.6274,301.00,3.389000,460.390000,0.227000,-0.060800,4.901640,"{'CO2': 0.04, 'N2': 0.044, 'C1': 0.067, 'C2': ...",0
8,nC5,0.017292,72.151,0.6301,309.22,3.370000,469.590000,0.251000,-0.039000,4.869612,"{'CO2': 0, 'N2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",0
9,C6,0.022392,86.178,0.6900,337.05,3.104000,507.500000,0.252000,-0.008000,5.926800,"{'CO2': 0.05, 'N2': 0.054, 'C1': 0.042, 'C2': ...",1
10,C7,0.032003,96.000,0.7270,365.05,3.138442,533.539281,0.306969,-0.039968,6.129490,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
11,C8,0.040134,107.000,0.7490,389.85,2.956857,553.255602,0.346274,-0.014077,6.781567,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
12,C9,0.029443,121.000,0.7680,415.35,2.743737,575.052576,0.394487,0.014491,7.657889,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
13,C10,0.025343,134.000,0.7820,438.95,2.572131,593.274803,0.437718,0.037589,8.488891,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
14,C11,0.020472,147.000,0.7930,460.35,2.416053,609.927686,0.479684,0.058077,9.338598,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
15,C12,0.017352,161.000,0.8040,481.45,2.268572,626.747369,0.523653,0.077782,10.255789,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
16,C13,0.016792,175.000,0.8150,500.35,2.139491,642.736213,0.566510,0.095481,11.166838,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
17,C14,0.014761,190.000,0.8260,519.55,2.013522,658.975483,0.611341,0.112604,12.144593,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
18,C15,0.012151,206.000,0.8360,539.15,1.887019,675.287628,0.658067,0.129122,13.201298,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
19,C16,0.010651,222.000,0.8430,556.15,1.763213,690.479097,0.703789,0.144131,14.292288,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
20,C17,0.009041,237.000,0.8510,573.15,1.660528,704.466862,0.745837,0.157037,15.293310,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
21,C18,0.008571,251.000,0.8560,586.15,1.564767,716.749565,0.784437,0.168206,16.260985,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
22,C19,0.008001,263.000,0.8610,598.15,1.489137,727.142166,0.817067,0.177185,17.079066,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
23,C20,0.006881,275.000,0.8660,611.15,1.417121,737.325647,0.849306,0.185673,17.895843,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
24,C21,0.005691,291.000,0.8710,624.15,1.322566,750.339037,0.891728,0.196305,19.011332,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
25,C22,0.005131,305.000,0.8760,636.15,1.245447,761.580729,0.928356,0.205034,19.975967,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
26,C23,0.004860,318.000,0.8810,648.15,1.177556,771.891492,0.961986,0.212708,20.863771,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
27,C24,0.004450,331.000,0.8850,659.15,1.110568,781.875437,0.995273,0.220005,21.769212,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
28,C25,0.003910,345.000,0.8880,670.15,1.039239,792.246255,1.030758,0.227478,22.770170,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
29,C26,0.003630,359.000,0.8920,681.15,0.972239,802.620422,1.065890,0.234587,23.751121,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
30,C27,0.003480,374.000,0.8960,692.15,0.902754,813.526294,1.103163,0.241834,24.807668,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
31,C28,0.002750,388.000,0.8990,702.15,0.839346,823.445652,1.137628,0.248281,25.810010,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
32,C29,0.002890,402.000,0.9020,711.15,0.778109,833.240286,1.171797,0.254448,26.812887,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
33,C30,0.002660,416.000,0.9050,719.15,0.718853,842.919147,1.205686,0.260356,27.816129,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
34,C31,0.002410,430.000,0.9090,728.15,0.662287,852.653378,1.239309,0.266024,28.794417,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
35,C32,0.002110,444.000,0.9120,736.15,0.606427,862.123957,1.272680,0.271469,29.797136,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
36,C33,0.001830,458.000,0.9150,744.15,0.552112,871.500520,1.305810,0.276706,30.799784,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
37,C34,0.001700,472.000,0.9170,751.15,0.498622,880.625853,1.338710,0.281750,31.829751,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
38,C35,0.001760,486.000,0.9200,759.15,0.447141,889.831562,1.371391,0.286612,32.832661,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
39,C36,0.021532,569.684,0.9220,766.15,0.161255,940.778229,1.562655,0.312472,39.346413,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1

In [ ]:
phase_env_rizari_daubert = PhaseDiagram(zi = krsnln_rizari_daubert_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_rizari_daubert.calc_phase_diagram('PREOS')
phase_env_rizari_data = phase_env_rizari_daubert.get_phase_diagram_data()

phase_env_pedersen = PhaseDiagram(zi = krsnln_pedersen_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_pedersen.calc_phase_diagram('PREOS')
phase_env_pedersen_data = phase_env_pedersen.get_phase_diagram_data()

phase_env_kesler_lee = PhaseDiagram(zi = krsnln_kesler_lee_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_kesler_lee.calc_phase_diagram('PREOS')
phase_env_kesler_lee_data = phase_env_kesler_lee.get_phase_diagram_data()

phase_env_sim_daubert = PhaseDiagram(zi = krsnln_sim_daubert_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_sim_daubert.calc_phase_diagram('PREOS')
phase_env_sim_daubert_data = phase_env_sim_daubert.get_phase_diagram_data()

phase_env_standing = PhaseDiagram(zi = krsnln_standing_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_standing.calc_phase_diagram('PREOS')
phase_env_standing_data = phase_env_standing.get_phase_diagram_data()

phase_env_twu = PhaseDiagram(zi = krsnln_twu_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_twu.calc_phase_diagram('PREOS')
phase_env_twu_data = phase_env_twu.get_phase_diagram_data()

phase_env_brs = PhaseDiagram(zi = krsnln_brs_composition, p_max=30, t_max=660, t_min=0, t_step=10)
phase_env_brs.calc_phase_diagram('PREOS')
phase_env_brs_data = phase_env_brs.get_phase_diagram_data()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns


sns.lineplot(marker='o',data = phase_env_rizari_data, x= phase_env_rizari_data['Temp'], y= phase_env_rizari_data['Up'], color = 'blue', label = 'Rizari-Daubert')
sns.lineplot(marker='o',data = phase_env_rizari_data, x= phase_env_rizari_data['Temp'], y= phase_env_rizari_data['Low'], color = 'blue')

sns.lineplot(marker='o',data = phase_env_pedersen_data, x= phase_env_pedersen_data['Temp'], y= phase_env_pedersen_data['Up'], color = 'red', label = 'Pedersen')
sns.lineplot(marker='o',data = phase_env_pedersen_data, x= phase_env_pedersen_data['Temp'], y= phase_env_pedersen_data['Low'], color = 'red')

sns.lineplot(marker='o',data = phase_env_kesler_lee_data, x= phase_env_kesler_lee_data['Temp'], y= phase_env_kesler_lee_data['Up'], color = 'green', label = 'Kesler_lee')
sns.lineplot(marker='o',data = phase_env_kesler_lee_data, x= phase_env_kesler_lee_data['Temp'], y= phase_env_kesler_lee_data['Low'], color = 'green')

sns.lineplot(marker='o',data = phase_env_sim_daubert_data, x= phase_env_sim_daubert_data['Temp'], y= phase_env_sim_daubert_data['Up'], color = 'blue', label = 'Sim_Daubert')
sns.lineplot(marker='o',data = phase_env_sim_daubert_data, x= phase_env_sim_daubert_data['Temp'], y= phase_env_sim_daubert_data['Low'], color = 'blue')

# sns.lineplot(marker='o',data = phase_env_standing_data, x= phase_env_standing_data['Temp'], y= phase_env_standing_data['Up'], color = 'gray', label = 'Standing')
# sns.lineplot(marker='o',data = phase_env_standing_data, x= phase_env_standing_data['Temp'], y= phase_env_standing_data['Low'], color = 'gray')

# sns.lineplot(marker='o',data = phase_env_twu_data, x= phase_env_twu_data['Temp'], y= phase_env_twu_data['Up'], color = 'yellow', label = 'Twu')
# sns.lineplot(marker='o',data = phase_env_twu_data, x= phase_env_twu_data['Temp'], y= phase_env_twu_data['Low'], color = 'yellow')

sns.lineplot(marker='',data = phase_env_brs_data, x= phase_env_brs_data['Temp'], y= phase_env_brs_data['Up'], color = 'black', label = 'Brusilovsky')
sns.lineplot(marker='',data = phase_env_brs_data, x= phase_env_brs_data['Temp'], y= phase_env_brs_data['Low'], color = 'black')

sns.scatterplot(x=[65], y = [13], color = 'green', label = 'Psat_fact', marker ='x')
plt.title('Krasnoleninskoe Phase Envelope')
plt.xlabel('Temperature, C')
plt.ylabel('Pressure, MPa')

# PRRZLM №200839

In [ ]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\prrzlm.xlsx')
przlm_dict = excel_loader.load(header=True, sheet='to_model')

### Фактические данные

In [ ]:
p_sat = 120.47

## Создаем базовую модель и сравниваемся с PVTSIM

In [ ]:
przlm_comp = Composition(przlm_dict)

In [ ]:
przlm_comp.COMPOSITION_PROPERTIES

In [ ]:
przlm_model = CompositionalModel(przlm_comp)

In [ ]:
conds = Conditions(5,50)

In [ ]:
przlm_model.flash(conds)

In [ ]:
przlm_model.saturation_pressure(60)

### Проверяем сепаратор тест

In [ ]:
przlm_model.experiments.SEPARATORTEST.calculate_3stages([0.7, 0.5, 0.1], [20, 20, 20])

## Начинаем играть корреляциями

In [ ]:
prr_base_comp = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'rizari_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
prr_base_comp.edit_component_properties('C36', {'molar_mass' : 523.941})

In [ ]:
prr_base_comp.COMPOSITION_PROPERTIES

In [ ]:
prr_pedersen_comp = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
prr_pedersen_comp.edit_component_properties('C36', {'molar_mass' : 523.941})

### Какие то расчеты, можно и убрать

In [ ]:
model_base = CompositionalModel(prr_base_comp)
model_kesler = CompositionalModel(prr_pedersen_comp)

In [ ]:
model_kesler.experiments.SEPARATORTEST_MOD.calculate(150, 60, [0.76,0.3,0.101], [55, 58.3, 20])

In [ ]:
model_base.saturation_pressure(58)

In [ ]:
dleresview = DLEResultsViewer()
dleresview.view(model_kesler.experiments.SEPARATORTEST_MOD.result)

### Расчет фазовой по корреляции Ризари-Дауберта

In [ ]:
phase_env_prr_rizari_daubert = PhaseDiagram(prr_base_comp, p_max=35, t_max= 550, t_min=0, t_step=10)

In [ ]:
phase_env_prr_rizari_daubert.calc_phase_diagram('PREOS')

In [ ]:
phase_env_data_1 = phase_env_prr_rizari_daubert.get_phase_diagram_data()

### Расчет фазовой по корреляции Pedersen

In [ ]:
phase_env_prr_pedersen = PhaseDiagram(prr_pedersen_comp, p_max=35, t_max= 550, t_min=0, t_step=10)
phase_env_prr_pedersen.calc_phase_diagram('PREOS')

In [ ]:
phase_env_data_2 = phase_env_prr_pedersen.get_phase_diagram_data()

### Расчет по корреляции Kesler-Lee

In [ ]:
prr_kesler_lee_comp = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'kesler_lee',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
prr_kesler_lee_comp.edit_component_properties('C36', {'molar_mass' : 523.941})

In [ ]:
phase_env_prr_kesler_lee = PhaseDiagram(prr_kesler_lee_comp, p_max=35, t_max= 550, t_min=0, t_step=10)
phase_env_prr_kesler_lee.calc_phase_diagram('PREOS')

In [ ]:
phase_env_data_3 = phase_env_prr_kesler_lee.get_phase_diagram_data()

###  Расчет по корреляции Sim-Daubert

In [ ]:
prr_sim_daubert_comp = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'sim_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
prr_sim_daubert_comp.edit_component_properties('C36', {'molar_mass' : 523.941})

In [ ]:
phase_env_prr_sim_daubert = PhaseDiagram(prr_sim_daubert_comp, p_max=35, t_max= 550, t_min=0, t_step=10)
phase_env_prr_sim_daubert.calc_phase_diagram('PREOS')

In [ ]:
phase_env_data_4 = phase_env_prr_sim_daubert.get_phase_diagram_data()

### Pc Br

In [ ]:
prr_pc_eos_comp = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pc_from_eos',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
prr_pc_eos_comp.edit_component_properties('C36', {'molar_mass' : 523.941})

In [ ]:
phase_env_prr_brs = PhaseDiagram(prr_pc_eos_comp, p_max=35, t_max= 550, t_min=0, t_step=10)
phase_env_prr_brs.calc_phase_diagram('PREOS')
phase_env_data_5 = phase_env_prr_brs.get_phase_diagram_data()

## Построение общей фазовой и сравнение результатов

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns


sns.lineplot(marker='o',data = phase_env_data_1, x= phase_env_data_1['Temp'], y= phase_env_data_1['Up'], color = 'blue', label = 'Rizari-Daubert')
sns.lineplot(marker='o',data = phase_env_data_1, x= phase_env_data_1['Temp'], y= phase_env_data_1['Low'], color = 'blue')
sns.lineplot(marker='o',data = phase_env_data_2, x= phase_env_data_2['Temp'], y= phase_env_data_2['Up'], color = 'red', label = 'Pedersen')
sns.lineplot(marker='o',data = phase_env_data_2, x= phase_env_data_2['Temp'], y= phase_env_data_2['Low'], color = 'red')
sns.lineplot(marker='o',data = phase_env_data_3, x= phase_env_data_3['Temp'], y= phase_env_data_3['Up'], color = 'gray', label = 'Kesler-Lee')
sns.lineplot(marker='o',data = phase_env_data_3, x= phase_env_data_3['Temp'], y= phase_env_data_3['Low'], color = 'gray')
sns.lineplot(marker='o',data = phase_env_data_4, x= phase_env_data_4['Temp'], y= phase_env_data_4['Up'], color = 'black', label = 'Sim-Daubert')
sns.lineplot(marker='o',data = phase_env_data_4, x= phase_env_data_4['Temp'], y= phase_env_data_4['Low'], color = 'black')
sns.lineplot(marker='o',data = phase_env_data_5, x= phase_env_data_5['Temp'], y= phase_env_data_5['Up'], color = 'green', label = 'Brusilovsky')
sns.lineplot(marker='o',data = phase_env_data_5, x= phase_env_data_5['Temp'], y= phase_env_data_5['Low'], color = 'green')
sns.scatterplot(x=[65], y = [13], color = 'green', label = 'Psat_fact')
plt.title('Prirazlomnoe Phase Envelope')
plt.xlabel('Temperature, C')
plt.ylabel('Pressure, MPa')

# ZAP_MES

In [ ]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\zap_mes.xlsx')
zap_mes_dict = excel_loader.load(header=True, sheet='to_model')

In [ ]:
zap_mes_comp = Composition(zap_mes_dict)

In [ ]:
phase_env_zap_mes = PhaseDiagram(zi = zap_mes_comp, p_max=14, t_min=0, t_max=750, t_step= 10)

In [ ]:
phase_env_zap_mes.calc_phase_diagram('PREOS')

In [ ]:
zap_mes_phase_data = phase_env_zap_mes.get_phase_diagram_data()

In [ ]:
import seaborn as sns

In [ ]:
sns.lineplot(marker='o',data = zap_mes_phase_data, x= zap_mes_phase_data['Temp'], y= zap_mes_phase_data['Up'], color = 'blue', label = 'base')
sns.lineplot(marker='o',data = zap_mes_phase_data, x= zap_mes_phase_data['Temp'], y= zap_mes_phase_data['Low'], color = 'blue')

# NP

In [ ]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\np.xlsx')
np_dict = excel_loader.load(header=True, sheet='to_model')

### Для различных УРС

#### Расчет УРС АИ

In [ ]:
base_comp = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
model_ai = CompositionalModel(base_comp, eos = 'BRSEOS')

In [ ]:
conds = Conditions(5,50)
model_ai.flash(conds)

#### Расчет фазовой для уравнения АИ

In [ ]:
phase_env_ai = PhaseDiagram(base_comp, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_ai.calc_phase_diagram('BRSEOS')

In [ ]:
phase_env_ai_data = phase_env_ai.get_phase_diagram_data()

#### Расчет фазовой для PR

In [ ]:
phase_env_pr = PhaseDiagram(base_comp, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_pr.calc_phase_diagram('PREOS')

In [ ]:
phase_env_pr_data = phase_env_pr.get_phase_diagram_data()

#### Расчет фазовой для SRK

In [ ]:
phase_env_srk = PhaseDiagram(base_comp, p_max=20, t_min=0, t_max=550, t_step=10)
phase_env_srk.calc_phase_diagram('SRKEOS')

In [ ]:
phase_env_srk_data = phase_env_srk.get_phase_diagram_data()

#### Сравнение фазовых AI, SRK и PR

In [ ]:
import seaborn as sns

In [ ]:
sns.lineplot(marker='o',data = phase_env_ai_data, x= phase_env_ai_data['Temp'], y= phase_env_ai_data['Up'], color = 'blue', label = 'BRSEOS')
sns.lineplot(marker='o',data = phase_env_ai_data, x= phase_env_ai_data['Temp'], y= phase_env_ai_data['Low'], color = 'blue')
sns.lineplot(marker='o',data = phase_env_pr_data, x= phase_env_pr_data['Temp'], y= phase_env_pr_data['Up'], color = 'red', label = 'PREOS')
sns.lineplot(marker='o',data = phase_env_pr_data, x= phase_env_pr_data['Temp'], y= phase_env_pr_data['Low'], color = 'red')
sns.lineplot(marker='o',data = phase_env_srk_data, x= phase_env_srk_data['Temp'], y= phase_env_srk_data['Up'], color = 'green', label = 'SRKEOS')
sns.lineplot(marker='o',data = phase_env_srk_data, x= phase_env_srk_data['Temp'], y= phase_env_srk_data['Low'], color = 'green')

### Rizari_daubert

In [ ]:
np_comp_rizari_daubert = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'rizari_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_rd = PhaseDiagram(np_comp_rizari_daubert, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_rd.calc_phase_diagram('PREOS')

In [ ]:
np_data_rizari_daubert = phase_env_rd.get_phase_diagram_data()

### pedersen

In [ ]:
np_comp_pedersen = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_pd = PhaseDiagram(np_comp_pedersen, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_pd.calc_phase_diagram('PREOS')
np_data_pedersen = phase_env_pd.get_phase_diagram_data()

### Kesler-Lee

In [ ]:
np_comp_kesler_lee = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'kesler_lee',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_kl = PhaseDiagram(np_comp_kesler_lee, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_kl.calc_phase_diagram('PREOS')
np_data_kesler_lee = phase_env_kl.get_phase_diagram_data()

### Sim_Daubert

In [ ]:
np_comp_sim_daubert = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'sim_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_sd = PhaseDiagram(np_comp_sim_daubert, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_sd.calc_phase_diagram('PREOS')
np_data_sim_d = phase_env_sd.get_phase_diagram_data()

### Standing

In [ ]:
np_comp_standing = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'standing',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_std = PhaseDiagram(np_comp_standing, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_std.calc_phase_diagram('PREOS')
np_data_std = phase_env_std.get_phase_diagram_data()

### Twu

In [ ]:
np_comp_standing.COMPOSITION

In [ ]:
np_comp_twu = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'twu',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_twu = PhaseDiagram(np_comp_twu, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_twu.calc_phase_diagram('PREOS')
np_data_twu = phase_env_twu.get_phase_diagram_data()

### BRS

In [ ]:
np_comp_brs = Composition(np_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pc_from_eos',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [ ]:
phase_env_brs = PhaseDiagram(np_comp_brs, p_max=25, t_min=0, t_max=550, t_step=10)
phase_env_brs.calc_phase_diagram('PREOS')
np_data_brs = phase_env_brs.get_phase_diagram_data()

## Свод график

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
sns.lineplot(marker='o',data = np_data_rizari_daubert, x= np_data_rizari_daubert['Temp'], y= np_data_rizari_daubert['Up'], color = 'blue', label = 'Rizari-Daubert')
sns.lineplot(marker='o',data = np_data_rizari_daubert, x= np_data_rizari_daubert['Temp'], y= np_data_rizari_daubert['Low'], color = 'blue')
sns.lineplot(marker='o',data = np_data_pedersen, x= np_data_pedersen['Temp'], y= np_data_pedersen['Up'], color = 'red', label = 'Pedersen')
sns.lineplot(marker='o',data = np_data_pedersen, x= np_data_pedersen['Temp'], y= np_data_pedersen['Low'], color = 'red')
sns.lineplot(marker='o',data = np_data_kesler_lee, x= np_data_kesler_lee['Temp'], y= np_data_kesler_lee['Up'], color = 'green', label = 'Kesler-Lee')
sns.lineplot(marker='o',data = np_data_kesler_lee, x= np_data_kesler_lee['Temp'], y= np_data_kesler_lee['Low'], color = 'green')
sns.lineplot(marker='o',data = np_data_sim_d, x= np_data_sim_d['Temp'], y= np_data_sim_d['Up'], color = 'gray', label = 'Sim-Daubert')
sns.lineplot(marker='o',data = np_data_sim_d, x= np_data_sim_d['Temp'], y= np_data_sim_d['Low'], color = 'gray')
sns.lineplot(marker='o',data = np_data_brs, x= np_data_brs['Temp'], y= np_data_brs['Up'], color = 'orange', label = 'Brusilovskiy')
sns.lineplot(marker='o',data = np_data_brs, x= np_data_brs['Temp'], y= np_data_brs['Low'], color = 'orange')
sns.lineplot(marker='o',data = np_data_twu, x= np_data_twu['Temp'], y= np_data_twu['Up'], color = 'black', label = 'Twu')
sns.lineplot(marker='o',data = np_data_twu, x= np_data_twu['Temp'], y= np_data_twu['Low'], color = 'black')
# sns.lineplot(marker='o',data = np_data_std, x= np_data_std['Temp'], y= np_data_std['Up'], color = 'gray', label = 'Standing')
# sns.lineplot(marker='o',data = np_data_std, x= np_data_std['Temp'], y= np_data_std['Low'], color = 'gray')
sns.scatterplot(x=[57.7], y = [11.7], label = 'Psat_fact', marker = 'x')
plt.title('Novoport phase envelope')
plt.ylabel('Pressure, MPa')
plt.xlabel('Temp, C')